/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`get_client`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClientError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_client_list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClientListError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status410(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`verify_client`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyClientError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// Returns the details of a client.
pub async fn get_client(configuration: &configuration::Configuration, client_id: &str) -> Result<models::Client, Error<GetClientError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_client_id = client_id;

	let uri_str = format!(
		"{}/clients/{client_id}",
		configuration.base_path,
		client_id = crate::apis::urlencode(p_path_client_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::Client`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::Client`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<GetClientError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Returns a list of all clients. The clients are returned sorted by creation date, with the newest clients appearing first. Warning: the endpoint is being deprecated and will be removed in future versions.
#[deprecated]
pub async fn get_client_list(
	configuration: &configuration::Configuration,
	paginated: Option<bool>,
	limit: Option<u32>,
	offset: Option<u32>,
) -> Result<Vec<models::Client>, Error<GetClientListError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_query_paginated = paginated;
	let p_query_limit = limit;
	let p_query_offset = offset;

	let uri_str = format!("{}/clients", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref param_value) = p_query_paginated {
		req_builder = req_builder.query(&[("paginated", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Client&gt;`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Client&gt;`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<GetClientListError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Verifies the client in the provided token
pub async fn verify_client(
	configuration: &configuration::Configuration,
	verify_client_request: Option<models::VerifyClientRequest>,
) -> Result<models::Client, Error<VerifyClientError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_verify_client_request = verify_client_request;

	let uri_str = format!("{}/clients/verify", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_verify_client_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::Client`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::Client`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<VerifyClientError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
