/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`add_domain`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddDomainError {
	Status400(models::ClerkErrors),
	Status402(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_domain`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteDomainError {
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListDomainsError {
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_domain`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateDomainError {
	Status400(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// Add a new domain for your instance. Useful in the case of multi-domain instances, allows adding satellite domains to an instance. The new domain must have a `name`. The domain name can contain the port for development instances, like `localhost:3000`. At the moment, instances can have only one primary domain, so the `is_satellite` parameter must be set to `true`. If you're planning to configure the new satellite domain to run behind a proxy, pass the `proxy_url` parameter accordingly.
pub async fn add_domain(
	configuration: &configuration::Configuration,
	add_domain_request: Option<models::AddDomainRequest>,
) -> Result<models::Domain, Error<AddDomainError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_add_domain_request = add_domain_request;

	let uri_str = format!("{}/domains", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_add_domain_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::Domain`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::Domain`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<AddDomainError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Deletes a satellite domain for the instance. It is currently not possible to delete the instance's primary domain.
pub async fn delete_domain(configuration: &configuration::Configuration, domain_id: &str) -> Result<models::DeletedObject, Error<DeleteDomainError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_domain_id = domain_id;

	let uri_str = format!(
		"{}/domains/{domain_id}",
		configuration.base_path,
		domain_id = crate::apis::urlencode(p_path_domain_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::DeletedObject`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::DeletedObject`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<DeleteDomainError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Use this endpoint to get a list of all domains for an instance. The response will contain the primary domain for the instance and any satellite domains. Each domain in the response contains information about the URLs where Clerk operates and the required CNAME targets.
pub async fn list_domains(configuration: &configuration::Configuration) -> Result<models::Domains, Error<ListDomainsError>> {
	let uri_str = format!("{}/domains", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::Domains`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::Domains`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<ListDomainsError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// The `proxy_url` can be updated only for production instances. Update one of the instance's domains. Both primary and satellite domains can be updated. If you choose to use Clerk via proxy, use this endpoint to specify the `proxy_url`. Whenever you decide you'd rather switch to DNS setup for Clerk, simply set `proxy_url` to `null` for the domain. When you update a production instance's primary domain name, you have to make sure that you've completed all the necessary setup steps for DNS and emails to work. Expect downtime otherwise. Updating a primary domain's name will also update the instance's home origin, affecting the default application paths.
pub async fn update_domain(
	configuration: &configuration::Configuration,
	domain_id: &str,
	update_domain_request: models::UpdateDomainRequest,
) -> Result<models::Domain, Error<UpdateDomainError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_domain_id = domain_id;
	let p_body_update_domain_request = update_domain_request;

	let uri_str = format!(
		"{}/domains/{domain_id}",
		configuration.base_path,
		domain_id = crate::apis::urlencode(p_path_domain_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_update_domain_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::Domain`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::Domain`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<UpdateDomainError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
