/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`attempt_email_address_verification`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AttemptEmailAddressVerificationError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status500(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_email_address`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEmailAddressError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status409(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_email_address`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteEmailAddressError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status409(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_email_address`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEmailAddressError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`prepare_email_address_verification`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrepareEmailAddressVerificationError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status500(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`replace_user_email_address`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReplaceUserEmailAddressError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_email_address`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateEmailAddressError {
	Status400(models::ClerkErrors),
	Status401(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status409(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// Checks a one-time code against the verification identified by verification_id, and returns the verification with its updated status (`verified`, `unverified`, `expired`, or `failed`) and attempt count, so a backend driving its own frontend can react on every attempt — an incorrect or expired code is reported through the status, not as an error. Resubmitting a verification whose code was already accepted is rejected with a `verification_already_verified` error. If the code is correct and the email address is not already verified, it is also marked as verified as a side effect (just as it would be in a frontend verification flow); an already verified email address is left unchanged. It never creates a session; to sign the user in afterwards, mint a sign-in token.
pub async fn attempt_email_address_verification(
	configuration: &configuration::Configuration,
	email_address_id: &str,
	attempt_email_address_verification_request: models::AttemptEmailAddressVerificationRequest,
) -> Result<models::PrepareEmailAddressVerification200Response, Error<AttemptEmailAddressVerificationError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_email_address_id = email_address_id;
	let p_body_attempt_email_address_verification_request = attempt_email_address_verification_request;

	let uri_str = format!(
		"{}/email_addresses/{email_address_id}/attempt_verification",
		configuration.base_path,
		email_address_id = crate::apis::urlencode(p_path_email_address_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_attempt_email_address_verification_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::PrepareEmailAddressVerification200Response`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
				"Received `{unknown_type}` content type response that cannot be converted to `models::PrepareEmailAddressVerification200Response`"
			))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<AttemptEmailAddressVerificationError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Create a new email address
pub async fn create_email_address(
	configuration: &configuration::Configuration,
	create_email_address_request: Option<models::CreateEmailAddressRequest>,
) -> Result<models::EmailAddress, Error<CreateEmailAddressError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_create_email_address_request = create_email_address_request;

	let uri_str = format!("{}/email_addresses", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_create_email_address_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EmailAddress`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EmailAddress`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateEmailAddressError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Delete the email address with the given ID
pub async fn delete_email_address(
	configuration: &configuration::Configuration,
	email_address_id: &str,
) -> Result<models::DeletedObject, Error<DeleteEmailAddressError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_email_address_id = email_address_id;

	let uri_str = format!(
		"{}/email_addresses/{email_address_id}",
		configuration.base_path,
		email_address_id = crate::apis::urlencode(p_path_email_address_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::DeletedObject`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::DeletedObject`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<DeleteEmailAddressError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Returns the details of an email address.
pub async fn get_email_address(
	configuration: &configuration::Configuration,
	email_address_id: &str,
) -> Result<models::EmailAddress, Error<GetEmailAddressError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_email_address_id = email_address_id;

	let uri_str = format!(
		"{}/email_addresses/{email_address_id}",
		configuration.base_path,
		email_address_id = crate::apis::urlencode(p_path_email_address_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EmailAddress`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EmailAddress`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<GetEmailAddressError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Sends a one-time code to the given email address so that a backend can verify the user controls it (for example, in a custom, backend-driven sign-in flow). The code is tracked on its own verification; confirm it with attempt_verification.
pub async fn prepare_email_address_verification(
	configuration: &configuration::Configuration,
	email_address_id: &str,
) -> Result<models::PrepareEmailAddressVerification200Response, Error<PrepareEmailAddressVerificationError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_email_address_id = email_address_id;

	let uri_str = format!(
		"{}/email_addresses/{email_address_id}/prepare_verification",
		configuration.base_path,
		email_address_id = crate::apis::urlencode(p_path_email_address_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::PrepareEmailAddressVerification200Response`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
				"Received `{unknown_type}` content type response that cannot be converted to `models::PrepareEmailAddressVerification200Response`"
			))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<PrepareEmailAddressVerificationError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Replaces all of the user's email addresses with a single primary email address. By default the new email address is created verified, with the admin verification strategy. When `identification_status` is `reserved` it is created reserved instead: unverified but usable for sign-in and locked so no other user can claim it. When it is `unverified` the address is neither usable for sign-in nor locked. Any existing email addresses are deleted. If an existing email address is linked to a connected account, the request is rejected; remove the connected account first.  **Warning:** `identification_status: unverified` can lock the user out of their account. An unverified email address cannot be used to sign in, so if the user has no other verified or reserved identifier, deleting their existing email addresses leaves them unable to authenticate — and unable to verify the new address, since that requires signing in. Recovery then requires another admin API call.
pub async fn replace_user_email_address(
	configuration: &configuration::Configuration,
	user_id: &str,
	replace_user_email_address_request: models::ReplaceUserEmailAddressRequest,
) -> Result<models::EmailAddress, Error<ReplaceUserEmailAddressError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_user_id = user_id;
	let p_body_replace_user_email_address_request = replace_user_email_address_request;

	let uri_str = format!(
		"{}/users/{user_id}/email_address",
		configuration.base_path,
		user_id = crate::apis::urlencode(p_path_user_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_replace_user_email_address_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EmailAddress`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EmailAddress`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<ReplaceUserEmailAddressError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Updates an email address.
pub async fn update_email_address(
	configuration: &configuration::Configuration,
	email_address_id: &str,
	update_email_address_request: Option<models::UpdateEmailAddressRequest>,
) -> Result<models::EmailAddress, Error<UpdateEmailAddressError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_email_address_id = email_address_id;
	let p_body_update_email_address_request = update_email_address_request;

	let uri_str = format!(
		"{}/email_addresses/{email_address_id}",
		configuration.base_path,
		email_address_id = crate::apis::urlencode(p_path_email_address_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_update_email_address_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EmailAddress`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EmailAddress`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<UpdateEmailAddressError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
