/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_enterprise_connection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEnterpriseConnectionError {
	Status402(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status409(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_enterprise_connection_test_run`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEnterpriseConnectionTestRunError {
	Status402(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_enterprise_connection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteEnterpriseConnectionError {
	Status402(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_enterprise_connection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEnterpriseConnectionError {
	Status402(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_enterprise_connection_test_runs`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEnterpriseConnectionTestRunsError {
	Status402(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_enterprise_connections`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEnterpriseConnectionsError {
	Status402(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_enterprise_connection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateEnterpriseConnectionError {
	Status400(models::ClerkErrors),
	Status402(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// Create a new enterprise connection.
pub async fn create_enterprise_connection(
	configuration: &configuration::Configuration,
	create_enterprise_connection_request: Option<models::CreateEnterpriseConnectionRequest>,
) -> Result<models::EnterpriseConnection, Error<CreateEnterpriseConnectionError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_create_enterprise_connection_request = create_enterprise_connection_request;

	let uri_str = format!("{}/enterprise_connections", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_create_enterprise_connection_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EnterpriseConnection`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EnterpriseConnection`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateEnterpriseConnectionError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Returns a short-lived URL that starts the IdP test flow for this connection.
pub async fn create_enterprise_connection_test_run(
	configuration: &configuration::Configuration,
	enterprise_connection_id: &str,
) -> Result<models::EnterpriseConnectionTestRunResponse, Error<CreateEnterpriseConnectionTestRunError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_enterprise_connection_id = enterprise_connection_id;

	let uri_str = format!(
		"{}/enterprise_connections/{enterprise_connection_id}/test_runs",
		configuration.base_path,
		enterprise_connection_id = crate::apis::urlencode(p_path_enterprise_connection_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EnterpriseConnectionTestRunResponse`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EnterpriseConnectionTestRunResponse`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateEnterpriseConnectionTestRunError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Deletes the enterprise connection whose ID matches the provided `enterprise_connection_id` in the path.
pub async fn delete_enterprise_connection(
	configuration: &configuration::Configuration,
	enterprise_connection_id: &str,
) -> Result<models::DeletedObject, Error<DeleteEnterpriseConnectionError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_enterprise_connection_id = enterprise_connection_id;

	let uri_str = format!(
		"{}/enterprise_connections/{enterprise_connection_id}",
		configuration.base_path,
		enterprise_connection_id = crate::apis::urlencode(p_path_enterprise_connection_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::DeletedObject`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::DeletedObject`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<DeleteEnterpriseConnectionError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Fetches the enterprise connection whose ID matches the provided `enterprise_connection_id` in the path.
pub async fn get_enterprise_connection(
	configuration: &configuration::Configuration,
	enterprise_connection_id: &str,
) -> Result<models::EnterpriseConnection, Error<GetEnterpriseConnectionError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_enterprise_connection_id = enterprise_connection_id;

	let uri_str = format!(
		"{}/enterprise_connections/{enterprise_connection_id}",
		configuration.base_path,
		enterprise_connection_id = crate::apis::urlencode(p_path_enterprise_connection_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EnterpriseConnection`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EnterpriseConnection`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<GetEnterpriseConnectionError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Returns a paginated list of SAML or OIDC debug test runs for an enterprise connection.
pub async fn list_enterprise_connection_test_runs(
	configuration: &configuration::Configuration,
	enterprise_connection_id: &str,
	status: Option<Vec<String>>,
	limit: Option<u32>,
	offset: Option<u32>,
) -> Result<models::EnterpriseConnectionTestRuns, Error<ListEnterpriseConnectionTestRunsError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_enterprise_connection_id = enterprise_connection_id;
	let p_query_status = status;
	let p_query_limit = limit;
	let p_query_offset = offset;

	let uri_str = format!(
		"{}/enterprise_connections/{enterprise_connection_id}/test_runs",
		configuration.base_path,
		enterprise_connection_id = crate::apis::urlencode(p_path_enterprise_connection_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref param_value) = p_query_status {
		req_builder = match "multi" {
			"multi" => req_builder.query(
				&param_value
					.into_iter()
					.map(|p| ("status".to_owned(), p.to_string()))
					.collect::<Vec<(std::string::String, std::string::String)>>(),
			),
			_ => req_builder.query(&[(
				"status",
				&param_value
					.into_iter()
					.map(|p| p.to_string())
					.collect::<Vec<String>>()
					.join(",")
					.to_string(),
			)]),
		};
	}
	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EnterpriseConnectionTestRuns`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EnterpriseConnectionTestRuns`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<ListEnterpriseConnectionTestRunsError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Returns the list of enterprise connections for the instance. Results can be paginated using the optional `limit` and `offset` query parameters.
pub async fn list_enterprise_connections(
	configuration: &configuration::Configuration,
	limit: Option<u32>,
	offset: Option<u32>,
	organization_id: Option<&str>,
	active: Option<bool>,
) -> Result<models::EnterpriseConnections, Error<ListEnterpriseConnectionsError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_query_limit = limit;
	let p_query_offset = offset;
	let p_query_organization_id = organization_id;
	let p_query_active = active;

	let uri_str = format!("{}/enterprise_connections", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_organization_id {
		req_builder = req_builder.query(&[("organization_id", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_active {
		req_builder = req_builder.query(&[("active", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EnterpriseConnections`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EnterpriseConnections`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<ListEnterpriseConnectionsError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Updates the enterprise connection whose ID matches the provided `enterprise_connection_id` in the path. When enabling the connection (setting `active` to true), any existing verified organization domains that match the connection's domains (e.g. used for enrollment modes like automatic invitation) may be deleted so the connection can be enabled.
pub async fn update_enterprise_connection(
	configuration: &configuration::Configuration,
	enterprise_connection_id: &str,
	update_enterprise_connection_request: models::UpdateEnterpriseConnectionRequest,
) -> Result<models::EnterpriseConnection, Error<UpdateEnterpriseConnectionError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_enterprise_connection_id = enterprise_connection_id;
	let p_body_update_enterprise_connection_request = update_enterprise_connection_request;

	let uri_str = format!(
		"{}/enterprise_connections/{enterprise_connection_id}",
		configuration.base_path,
		enterprise_connection_id = crate::apis::urlencode(p_path_enterprise_connection_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_update_enterprise_connection_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::EnterpriseConnection`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::EnterpriseConnection`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<UpdateEnterpriseConnectionError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
