/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_m2_m_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateM2MTokenError {
	Status400(models::CreateAdminPortalLinkToken400Response),
	Status409(models::CreateAdminPortalLinkToken401Response),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_m2_m_tokens`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetM2MTokensError {
	Status400(models::CreateAdminPortalLinkToken400Response),
	Status403(models::CreateAdminPortalLinkToken401Response),
	Status404(models::CreateAdminPortalLinkToken401Response),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`revoke_m2_m_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevokeM2MTokenError {
	Status400(models::CreateAdminPortalLinkToken400Response),
	Status404(models::CreateAdminPortalLinkToken401Response),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`verify_m2_m_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyM2MTokenError {
	Status400(models::CreateAdminPortalLinkToken400Response),
	Status404(models::CreateAdminPortalLinkToken401Response),
	UnknownValue(serde_json::Value),
}

/// Creates a new M2M Token. Must be authenticated via a Machine Secret Key.
pub async fn create_m2_m_token(
	configuration: &configuration::Configuration,
	create_m2_m_token_request: models::CreateM2MTokenRequest,
) -> Result<models::CreateM2MToken201Response, Error<CreateM2MTokenError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_create_m2_m_token_request = create_m2_m_token_request;

	let uri_str = format!("{}/m2m_tokens", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_create_m2_m_token_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::CreateM2MToken201Response`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::CreateM2MToken201Response`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateM2MTokenError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Fetches M2M tokens for a specific machine.  Only tokens created with the opaque token format are returned by this endpoint. JWT-format M2M tokens are stateless and are not stored.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When fetching M2M tokens with a Machine Secret Key, only tokens associated with the authenticated machine can be retrieved. - When fetching M2M tokens with a Clerk Secret Key, tokens for any machine in the instance can be retrieved.
pub async fn get_m2_m_tokens(
	configuration: &configuration::Configuration,
	subject: &str,
	revoked: Option<bool>,
	expired: Option<bool>,
	limit: Option<f64>,
	offset: Option<f64>,
) -> Result<models::GetM2MTokens200Response, Error<GetM2MTokensError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_query_subject = subject;
	let p_query_revoked = revoked;
	let p_query_expired = expired;
	let p_query_limit = limit;
	let p_query_offset = offset;

	let uri_str = format!("{}/m2m_tokens", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	req_builder = req_builder.query(&[("subject", &p_query_subject.to_string())]);
	if let Some(ref param_value) = p_query_revoked {
		req_builder = req_builder.query(&[("revoked", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_expired {
		req_builder = req_builder.query(&[("expired", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::GetM2MTokens200Response`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::GetM2MTokens200Response`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<GetM2MTokensError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Revokes a M2M Token.  This endpoint only revokes stored opaque-format M2M tokens. JWT-format M2M tokens are stateless and cannot be revoked.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When revoking a M2M Token with a Machine Secret Key, the token must managed by the Machine associated with the Machine Secret Key. - When revoking a M2M Token with a Clerk Secret Key, any token on the Instance can be revoked.
pub async fn revoke_m2_m_token(
	configuration: &configuration::Configuration,
	m2m_token_id: &str,
	revoke_admin_portal_link_token_request: models::RevokeAdminPortalLinkTokenRequest,
) -> Result<models::GetM2MTokens200ResponseM2mTokensInner, Error<RevokeM2MTokenError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_m2m_token_id = m2m_token_id;
	let p_body_revoke_admin_portal_link_token_request = revoke_admin_portal_link_token_request;

	let uri_str = format!(
		"{}/m2m_tokens/{m2m_token_id}/revoke",
		configuration.base_path,
		m2m_token_id = crate::apis::urlencode(p_path_m2m_token_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_revoke_admin_portal_link_token_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::GetM2MTokens200ResponseM2mTokensInner`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::GetM2MTokens200ResponseM2mTokensInner`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<RevokeM2MTokenError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Verifies a M2M Token.  This endpoint can be authenticated by either a Machine Secret Key or by a Clerk Secret Key.  - When verifying a M2M Token with a Machine Secret Key, the token must be granted access to the Machine associated with the Machine Secret Key. - When verifying a M2M Token with a Clerk Secret Key, any token on the Instance can be verified.
pub async fn verify_m2_m_token(
	configuration: &configuration::Configuration,
	verify_m2_m_token_request: models::VerifyM2MTokenRequest,
) -> Result<models::GetM2MTokens200ResponseM2mTokensInner, Error<VerifyM2MTokenError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_verify_m2_m_token_request = verify_m2_m_token_request;

	let uri_str = format!("{}/m2m_tokens/verify", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_verify_m2_m_token_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::GetM2MTokens200ResponseM2mTokensInner`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::GetM2MTokens200ResponseM2mTokensInner`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<VerifyM2MTokenError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
