/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_organization_invitation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOrganizationInvitationError {
	Status400(models::ClerkErrors),
	Status402(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_organization_invitation_bulk`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOrganizationInvitationBulkError {
	Status400(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_organization_invitation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetOrganizationInvitationError {
	Status400(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_instance_organization_invitations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListInstanceOrganizationInvitationsError {
	Status400(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status422(models::ClerkErrors),
	Status500(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_organization_invitations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListOrganizationInvitationsError {
	Status400(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_pending_organization_invitations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListPendingOrganizationInvitationsError {
	Status400(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`revoke_organization_invitation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevokeOrganizationInvitationError {
	Status400(models::ClerkErrors),
	Status403(models::ClerkErrors),
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// Creates a new organization invitation and sends an email to the provided `email_address` with a link to accept the invitation and join the organization. You can specify the `role` for the invited organization member.  New organization invitations get a \"pending\" status until they are revoked by an organization administrator or accepted by the invitee.  The request body supports passing an optional `redirect_url` parameter. When the invited user clicks the link to accept the invitation, they will be redirected to the URL provided. Use this parameter to implement a custom invitation acceptance flow.  You can specify the ID of the user that will send the invitation with the `inviter_user_id` parameter. That user must be a member with administrator privileges in the organization. Only \"admin\" members can create organization invitations.  You can optionally provide public and private metadata for the organization invitation. The public metadata are visible by both the Frontend and the Backend whereas the private ones only by the Backend. When the organization invitation is accepted, the metadata will be transferred to the newly created organization membership.
pub async fn create_organization_invitation(
	configuration: &configuration::Configuration,
	organization_id: &str,
	create_organization_invitation_request: Option<models::CreateOrganizationInvitationRequest>,
) -> Result<models::OrganizationInvitation, Error<CreateOrganizationInvitationError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_organization_id = organization_id;
	let p_body_create_organization_invitation_request = create_organization_invitation_request;

	let uri_str = format!(
		"{}/organizations/{organization_id}/invitations",
		configuration.base_path,
		organization_id = crate::apis::urlencode(p_path_organization_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_create_organization_invitation_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::OrganizationInvitation`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationInvitation`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateOrganizationInvitationError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Creates new organization invitations in bulk and sends out emails to the provided email addresses with a link to accept the invitation and join the organization.  This endpoint is limited to a maximum of 10 invitations per API call. If you need to send more invitations, please make multiple requests.  You can specify a different `role` for each invited organization member. New organization invitations get a \"pending\" status until they are revoked by an organization administrator or accepted by the invitee. The request body supports passing an optional `redirect_url` parameter for each invitation. When the invited user clicks the link to accept the invitation, they will be redirected to the provided URL. Use this parameter to implement a custom invitation acceptance flow. You can specify the ID of the user that will send the invitation with the `inviter_user_id` parameter. Each invitation can have a different inviter user. Inviter users must be members with administrator privileges in the organization. Only \"admin\" members can create organization invitations. You can optionally provide public and private metadata for each organization invitation. The public metadata are visible by both the Frontend and the Backend, whereas the private metadata are only visible by the Backend. When the organization invitation is accepted, the metadata will be transferred to the newly created organization membership.
pub async fn create_organization_invitation_bulk(
	configuration: &configuration::Configuration,
	organization_id: &str,
	create_organization_invitation_request: Vec<models::CreateOrganizationInvitationRequest>,
) -> Result<models::OrganizationInvitations, Error<CreateOrganizationInvitationBulkError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_organization_id = organization_id;
	let p_body_create_organization_invitation_request = create_organization_invitation_request;

	let uri_str = format!(
		"{}/organizations/{organization_id}/invitations/bulk",
		configuration.base_path,
		organization_id = crate::apis::urlencode(p_path_organization_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_create_organization_invitation_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::OrganizationInvitations`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationInvitations`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateOrganizationInvitationBulkError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Use this request to get an existing organization invitation by ID.
pub async fn get_organization_invitation(
	configuration: &configuration::Configuration,
	organization_id: &str,
	invitation_id: &str,
) -> Result<models::OrganizationInvitation, Error<GetOrganizationInvitationError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_organization_id = organization_id;
	let p_path_invitation_id = invitation_id;

	let uri_str = format!(
		"{}/organizations/{organization_id}/invitations/{invitation_id}",
		configuration.base_path,
		organization_id = crate::apis::urlencode(p_path_organization_id),
		invitation_id = crate::apis::urlencode(p_path_invitation_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::OrganizationInvitation`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationInvitation`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<GetOrganizationInvitationError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// This request returns the list of organization invitations for the instance. Results can be paginated using the optional `limit` and `offset` query parameters. You can filter them by providing the 'status' query parameter, that accepts multiple values. You can change the order by providing the 'order' query parameter, that accepts multiple values. You can filter by the invited user email address providing the `query` query parameter. The organization invitations are ordered by descending creation date by default.
pub async fn list_instance_organization_invitations(
	configuration: &configuration::Configuration,
	order_by: Option<&str>,
	status: Option<&str>,
	query: Option<&str>,
	limit: Option<u32>,
	offset: Option<u32>,
) -> Result<models::OrganizationInvitationsWithPublicOrganizationData, Error<ListInstanceOrganizationInvitationsError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_query_order_by = order_by;
	let p_query_status = status;
	let p_query_query = query;
	let p_query_limit = limit;
	let p_query_offset = offset;

	let uri_str = format!("{}/organization_invitations", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref param_value) = p_query_order_by {
		req_builder = req_builder.query(&[("order_by", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_status {
		req_builder = req_builder.query(&[("status", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_query {
		req_builder = req_builder.query(&[("query", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganizationInvitationsWithPublicOrganizationData`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationInvitationsWithPublicOrganizationData`")))),
        }
	} else {
		let content = resp.text().await?;
		let entity: Option<ListInstanceOrganizationInvitationsError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// This request returns the list of organization invitations. Results can be paginated using the optional `limit` and `offset` query parameters. You can filter them by providing the 'status' query parameter, that accepts multiple values. The organization invitations are ordered by descending creation date. Most recent invitations will be returned first. Any invitations created as a result of an Organization Domain are not included in the results.
pub async fn list_organization_invitations(
	configuration: &configuration::Configuration,
	organization_id: &str,
	status: Option<&str>,
	email_address: Option<&str>,
	order_by: Option<&str>,
	limit: Option<u32>,
	offset: Option<u32>,
) -> Result<models::OrganizationInvitations, Error<ListOrganizationInvitationsError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_organization_id = organization_id;
	let p_query_status = status;
	let p_query_email_address = email_address;
	let p_query_order_by = order_by;
	let p_query_limit = limit;
	let p_query_offset = offset;

	let uri_str = format!(
		"{}/organizations/{organization_id}/invitations",
		configuration.base_path,
		organization_id = crate::apis::urlencode(p_path_organization_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref param_value) = p_query_status {
		req_builder = req_builder.query(&[("status", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_email_address {
		req_builder = req_builder.query(&[("email_address", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_order_by {
		req_builder = req_builder.query(&[("order_by", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::OrganizationInvitations`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationInvitations`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<ListOrganizationInvitationsError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// This request returns the list of organization invitations with \"pending\" status. These are the organization invitations that can still be used to join the organization, but have not been accepted by the invited user yet. Results can be paginated using the optional `limit` and `offset` query parameters. The organization invitations are ordered by descending creation date. Most recent invitations will be returned first. Any invitations created as a result of an Organization Domain are not included in the results.
#[deprecated]
pub async fn list_pending_organization_invitations(
	configuration: &configuration::Configuration,
	organization_id: &str,
	limit: Option<u32>,
	offset: Option<u32>,
) -> Result<models::OrganizationInvitations, Error<ListPendingOrganizationInvitationsError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_organization_id = organization_id;
	let p_query_limit = limit;
	let p_query_offset = offset;

	let uri_str = format!(
		"{}/organizations/{organization_id}/invitations/pending",
		configuration.base_path,
		organization_id = crate::apis::urlencode(p_path_organization_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::OrganizationInvitations`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationInvitations`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<ListPendingOrganizationInvitationsError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Use this request to revoke a previously issued organization invitation. Revoking an organization invitation makes it invalid; the invited user will no longer be able to join the organization with the revoked invitation. Only organization invitations with \"pending\" status can be revoked. The request accepts the `requesting_user_id` parameter to specify the user which revokes the invitation. Only users with \"admin\" role can revoke invitations.
pub async fn revoke_organization_invitation(
	configuration: &configuration::Configuration,
	organization_id: &str,
	invitation_id: &str,
	revoke_organization_invitation_request: Option<models::RevokeOrganizationInvitationRequest>,
) -> Result<models::OrganizationInvitation, Error<RevokeOrganizationInvitationError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_organization_id = organization_id;
	let p_path_invitation_id = invitation_id;
	let p_body_revoke_organization_invitation_request = revoke_organization_invitation_request;

	let uri_str = format!(
		"{}/organizations/{organization_id}/invitations/{invitation_id}/revoke",
		configuration.base_path,
		organization_id = crate::apis::urlencode(p_path_organization_id),
		invitation_id = crate::apis::urlencode(p_path_invitation_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_revoke_organization_invitation_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::OrganizationInvitation`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::OrganizationInvitation`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<RevokeOrganizationInvitationError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
