/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_redirect_url`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRedirectUrlError {
	Status400(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_redirect_url`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteRedirectUrlError {
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_redirect_url`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRedirectUrlError {
	Status404(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_redirect_urls`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListRedirectUrlsError {
	UnknownValue(serde_json::Value),
}

/// Create a redirect URL
pub async fn create_redirect_url(
	configuration: &configuration::Configuration,
	create_redirect_url_request: Option<models::CreateRedirectUrlRequest>,
) -> Result<models::RedirectUrl, Error<CreateRedirectUrlError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_create_redirect_url_request = create_redirect_url_request;

	let uri_str = format!("{}/redirect_urls", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_create_redirect_url_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::RedirectUrl`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::RedirectUrl`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateRedirectUrlError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Remove the selected redirect URL from the whitelist of the instance
pub async fn delete_redirect_url(
	configuration: &configuration::Configuration,
	id: &str,
) -> Result<models::DeletedObject, Error<DeleteRedirectUrlError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_id = id;

	let uri_str = format!("{}/redirect_urls/{id}", configuration.base_path, id = crate::apis::urlencode(p_path_id));
	let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::DeletedObject`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::DeletedObject`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<DeleteRedirectUrlError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Retrieve the details of the redirect URL with the given ID
pub async fn get_redirect_url(configuration: &configuration::Configuration, id: &str) -> Result<models::RedirectUrl, Error<GetRedirectUrlError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_id = id;

	let uri_str = format!("{}/redirect_urls/{id}", configuration.base_path, id = crate::apis::urlencode(p_path_id));
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::RedirectUrl`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::RedirectUrl`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<GetRedirectUrlError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Lists all whitelisted redirect_urls for the instance
pub async fn list_redirect_urls(
	configuration: &configuration::Configuration,
	paginated: Option<bool>,
	limit: Option<u32>,
	offset: Option<u32>,
) -> Result<Vec<models::RedirectUrl>, Error<ListRedirectUrlsError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_query_paginated = paginated;
	let p_query_limit = limit;
	let p_query_offset = offset;

	let uri_str = format!("{}/redirect_urls", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref param_value) = p_query_paginated {
		req_builder = req_builder.query(&[("paginated", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `Vec&lt;models::RedirectUrl&gt;`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::RedirectUrl&gt;`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<ListRedirectUrlsError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
