/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_testing_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTestingTokenError {
	UnknownValue(serde_json::Value),
}

/// Retrieve a new testing token.
pub async fn create_testing_token(configuration: &configuration::Configuration) -> Result<models::TestingToken, Error<CreateTestingTokenError>> {
	let uri_str = format!("{}/testing_tokens", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::TestingToken`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::TestingToken`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateTestingTokenError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
