/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_bulk_waitlist_entries`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateBulkWaitlistEntriesError {
	Status400(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_waitlist_entry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWaitlistEntryError {
	Status400(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_waitlist_entry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteWaitlistEntryError {
	Status400(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status409(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`invite_waitlist_entry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InviteWaitlistEntryError {
	Status400(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status409(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_waitlist_entries`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListWaitlistEntriesError {
	UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`reject_waitlist_entry`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RejectWaitlistEntryError {
	Status400(models::ClerkErrors),
	Status404(models::ClerkErrors),
	Status409(models::ClerkErrors),
	Status422(models::ClerkErrors),
	UnknownValue(serde_json::Value),
}

/// Creates multiple waitlist entries for the provided email addresses. You can choose whether to send confirmation emails by setting the `notify` parameter to `true` or `false` for each entry. If the `notify` parameter is omitted, it defaults to `true`.  If an email address is already on the waitlist, no new entry will be created and the existing waitlist entry will be returned. Duplicate email addresses within the same request are not allowed.  This endpoint is limited to a maximum of 50 entries per API call. If you need to add more entries, please make multiple requests.
pub async fn create_bulk_waitlist_entries(
	configuration: &configuration::Configuration,
	create_bulk_waitlist_entries_request_inner: Option<Vec<models::CreateBulkWaitlistEntriesRequestInner>>,
) -> Result<Vec<models::WaitlistEntry>, Error<CreateBulkWaitlistEntriesError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_create_bulk_waitlist_entries_request_inner = create_bulk_waitlist_entries_request_inner;

	let uri_str = format!("{}/waitlist_entries/bulk", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_create_bulk_waitlist_entries_request_inner);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `Vec&lt;models::WaitlistEntry&gt;`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::WaitlistEntry&gt;`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateBulkWaitlistEntriesError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Creates a new waitlist entry for the given email address. If the email address is already on the waitlist, no new entry will be created and the existing waitlist entry will be returned.
pub async fn create_waitlist_entry(
	configuration: &configuration::Configuration,
	create_waitlist_entry_request: Option<models::CreateWaitlistEntryRequest>,
) -> Result<models::WaitlistEntry, Error<CreateWaitlistEntryError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_body_create_waitlist_entry_request = create_waitlist_entry_request;

	let uri_str = format!("{}/waitlist_entries", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_create_waitlist_entry_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::WaitlistEntry`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::WaitlistEntry`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<CreateWaitlistEntryError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Delete a pending waitlist entry.
pub async fn delete_waitlist_entry(
	configuration: &configuration::Configuration,
	waitlist_entry_id: &str,
) -> Result<models::DeletedObject, Error<DeleteWaitlistEntryError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_waitlist_entry_id = waitlist_entry_id;

	let uri_str = format!(
		"{}/waitlist_entries/{waitlist_entry_id}",
		configuration.base_path,
		waitlist_entry_id = crate::apis::urlencode(p_path_waitlist_entry_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::DeletedObject`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::DeletedObject`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<DeleteWaitlistEntryError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Send an invite to the email address in a waitlist entry.
pub async fn invite_waitlist_entry(
	configuration: &configuration::Configuration,
	waitlist_entry_id: &str,
	invite_waitlist_entry_request: Option<models::InviteWaitlistEntryRequest>,
) -> Result<models::WaitlistEntry, Error<InviteWaitlistEntryError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_waitlist_entry_id = waitlist_entry_id;
	let p_body_invite_waitlist_entry_request = invite_waitlist_entry_request;

	let uri_str = format!(
		"{}/waitlist_entries/{waitlist_entry_id}/invite",
		configuration.base_path,
		waitlist_entry_id = crate::apis::urlencode(p_path_waitlist_entry_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};
	req_builder = req_builder.json(&p_body_invite_waitlist_entry_request);

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::WaitlistEntry`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::WaitlistEntry`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<InviteWaitlistEntryError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Retrieve a list of waitlist entries for the instance. Entries are ordered by creation date in descending order by default. Supports filtering by email address or status and pagination with limit and offset parameters.
pub async fn list_waitlist_entries(
	configuration: &configuration::Configuration,
	limit: Option<u32>,
	offset: Option<u32>,
	query: Option<&str>,
	status: Option<&str>,
	order_by: Option<&str>,
) -> Result<models::ListWaitlistEntries200Response, Error<ListWaitlistEntriesError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_query_limit = limit;
	let p_query_offset = offset;
	let p_query_query = query;
	let p_query_status = status;
	let p_query_order_by = order_by;

	let uri_str = format!("{}/waitlist_entries", configuration.base_path);
	let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

	if let Some(ref param_value) = p_query_limit {
		req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_offset {
		req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_query {
		req_builder = req_builder.query(&[("query", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_status {
		req_builder = req_builder.query(&[("status", &param_value.to_string())]);
	}
	if let Some(ref param_value) = p_query_order_by {
		req_builder = req_builder.query(&[("order_by", &param_value.to_string())]);
	}
	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::ListWaitlistEntries200Response`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::ListWaitlistEntries200Response`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<ListWaitlistEntriesError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}

/// Reject a waitlist entry.
pub async fn reject_waitlist_entry(
	configuration: &configuration::Configuration,
	waitlist_entry_id: &str,
) -> Result<models::WaitlistEntry, Error<RejectWaitlistEntryError>> {
	// add a prefix to parameters to efficiently prevent name collisions
	let p_path_waitlist_entry_id = waitlist_entry_id;

	let uri_str = format!(
		"{}/waitlist_entries/{waitlist_entry_id}/reject",
		configuration.base_path,
		waitlist_entry_id = crate::apis::urlencode(p_path_waitlist_entry_id)
	);
	let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

	if let Some(ref user_agent) = configuration.user_agent {
		req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
	}
	if let Some(ref token) = configuration.bearer_access_token {
		req_builder = req_builder.bearer_auth(token.to_owned());
	};

	let req = req_builder.build()?;
	let resp = configuration.client.execute(req).await?;

	let status = resp.status();
	let content_type = resp
		.headers()
		.get("content-type")
		.and_then(|v| v.to_str().ok())
		.unwrap_or("application/octet-stream");
	let content_type = super::ContentType::from(content_type);

	if !status.is_client_error() && !status.is_server_error() {
		let content = resp.text().await?;
		match content_type {
			ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
			ContentType::Text => {
				return Err(Error::from(serde_json::Error::custom(
					"Received `text/plain` content type response that cannot be converted to `models::WaitlistEntry`",
				)))
			}
			ContentType::Unsupported(unknown_type) => {
				return Err(Error::from(serde_json::Error::custom(format!(
					"Received `{unknown_type}` content type response that cannot be converted to `models::WaitlistEntry`"
				))))
			}
		}
	} else {
		let content = resp.text().await?;
		let entity: Option<RejectWaitlistEntryError> = serde_json::from_str(&content).ok();
		Err(Error::ResponseError(ResponseContent { status, content, entity }))
	}
}
