/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeProductionInstanceDomainRequest {
	/// The new home URL of the production instance e.g. https://www.example.com
	#[serde(rename = "home_url", skip_serializing_if = "Option::is_none")]
	pub home_url: Option<String>,
	/// Whether this is a domain for a secondary app, meaning that any subdomain provided is significant and will be stored as part of the domain. This is useful for supporting multiple apps (one primary and multiple secondaries) on the same root domain (eTLD+1).
	#[serde(rename = "is_secondary", skip_serializing_if = "Option::is_none")]
	pub is_secondary: Option<bool>,
}

impl ChangeProductionInstanceDomainRequest {
	pub fn new() -> ChangeProductionInstanceDomainRequest {
		ChangeProductionInstanceDomainRequest {
			home_url: None,
			is_secondary: None,
		}
	}
}
