/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommercePlan {
	/// String representing the object's type. Objects of the same type share the same value.
	#[serde(rename = "object")]
	pub object: Object,
	/// Unique identifier for the plan.
	#[serde(rename = "id")]
	pub id: String,
	/// The name of the plan.
	#[serde(rename = "name")]
	pub name: String,
	#[serde(rename = "fee", deserialize_with = "Option::deserialize")]
	pub fee: Option<Box<models::CommerceMoneyResponse>>,
	#[serde(rename = "annual_monthly_fee", deserialize_with = "Option::deserialize")]
	pub annual_monthly_fee: Option<Box<models::CommerceMoneyResponse>>,
	#[serde(rename = "annual_fee", deserialize_with = "Option::deserialize")]
	pub annual_fee: Option<Box<models::CommerceMoneyResponse>>,
	/// The description of the plan.
	#[serde(rename = "description", deserialize_with = "Option::deserialize")]
	pub description: Option<String>,
	/// The ID of the product this plan belongs to.
	#[serde(rename = "product_id")]
	pub product_id: String,
	/// Whether this is the default plan.
	#[serde(rename = "is_default")]
	pub is_default: bool,
	/// Whether this is a recurring plan.
	#[serde(rename = "is_recurring")]
	pub is_recurring: bool,
	/// Whether this plan is publicly visible.
	#[serde(rename = "publicly_visible")]
	pub publicly_visible: bool,
	/// Whether this plan has a base fee.
	#[serde(rename = "has_base_fee")]
	pub has_base_fee: bool,
	/// The payer type this plan is designed for.
	#[serde(rename = "for_payer_type")]
	pub for_payer_type: String,
	/// The URL-friendly slug for the plan.
	#[serde(rename = "slug")]
	pub slug: String,
	/// The URL of the plan's avatar image.
	#[serde(rename = "avatar_url", deserialize_with = "Option::deserialize")]
	pub avatar_url: Option<String>,
	/// The features included in this plan.
	#[serde(rename = "features", skip_serializing_if = "Option::is_none")]
	pub features: Option<Vec<models::FeatureResponse>>,
	/// Whether free trial is enabled for this plan.
	#[serde(rename = "free_trial_enabled")]
	pub free_trial_enabled: bool,
	/// Number of free trial days for this plan.
	#[serde(rename = "free_trial_days", deserialize_with = "Option::deserialize")]
	pub free_trial_days: Option<i64>,
	/// Per-unit pricing tiers for this plan (for example, seats)
	#[serde(rename = "unit_prices", skip_serializing_if = "Option::is_none")]
	pub unit_prices: Option<Vec<models::CommercePlanUnitPrice>>,
}

impl CommercePlan {
	pub fn new(
		object: Object,
		id: String,
		name: String,
		fee: Option<models::CommerceMoneyResponse>,
		annual_monthly_fee: Option<models::CommerceMoneyResponse>,
		annual_fee: Option<models::CommerceMoneyResponse>,
		description: Option<String>,
		product_id: String,
		is_default: bool,
		is_recurring: bool,
		publicly_visible: bool,
		has_base_fee: bool,
		for_payer_type: String,
		slug: String,
		avatar_url: Option<String>,
		free_trial_enabled: bool,
		free_trial_days: Option<i64>,
	) -> CommercePlan {
		CommercePlan {
			object,
			id,
			name,
			fee: if let Some(x) = fee { Some(Box::new(x)) } else { None },
			annual_monthly_fee: if let Some(x) = annual_monthly_fee { Some(Box::new(x)) } else { None },
			annual_fee: if let Some(x) = annual_fee { Some(Box::new(x)) } else { None },
			description,
			product_id,
			is_default,
			is_recurring,
			publicly_visible,
			has_base_fee,
			for_payer_type,
			slug,
			avatar_url,
			features: None,
			free_trial_enabled,
			free_trial_days,
			unit_prices: None,
		}
	}
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "commerce_plan")]
	CommercePlan,
}

impl Default for Object {
	fn default() -> Object {
		Self::CommercePlan
	}
}
