/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommerceTotalsResponse2 {
	#[serde(rename = "subtotal")]
	pub subtotal: Box<models::CommerceMoneyResponse>,
	#[serde(rename = "base_fee")]
	pub base_fee: Box<models::CommerceMoneyResponse>,
	#[serde(rename = "tax_total")]
	pub tax_total: Box<models::CommerceMoneyResponse>,
	#[serde(rename = "grand_total")]
	pub grand_total: Box<models::CommerceMoneyResponse>,
	#[serde(rename = "per_unit_totals", skip_serializing_if = "Option::is_none")]
	pub per_unit_totals: Option<Vec<models::CommercePerUnitTotal2>>,
	#[serde(
		rename = "credits",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub credits: Option<Option<Box<models::CommerceCreditsResponse>>>,
	/// Information about the discounts applied to the payment
	#[serde(
		rename = "discounts",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub discounts: Option<Option<Box<models::BillingDiscountsResponse>>>,
}

impl CommerceTotalsResponse2 {
	pub fn new(
		subtotal: models::CommerceMoneyResponse,
		base_fee: models::CommerceMoneyResponse,
		tax_total: models::CommerceMoneyResponse,
		grand_total: models::CommerceMoneyResponse,
	) -> CommerceTotalsResponse2 {
		CommerceTotalsResponse2 {
			subtotal: Box::new(subtotal),
			base_fee: Box::new(base_fee),
			tax_total: Box::new(tax_total),
			grand_total: Box::new(grand_total),
			per_unit_totals: None,
			credits: None,
			discounts: None,
		}
	}
}
