/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommerceSubscriptionItem {
	/// String representing the object's type. Objects of the same type share the same value.
	#[serde(rename = "object")]
	pub object: Object,
	/// Unique identifier for the subscription item.
	#[serde(rename = "id")]
	pub id: String,
	/// Unique identifier for the Clerk instance.
	#[serde(rename = "instance_id")]
	pub instance_id: String,
	/// Current status of the subscription item.
	#[serde(rename = "status")]
	pub status: Status,
	#[serde(rename = "credit", skip_serializing_if = "Option::is_none")]
	pub credit: Option<Box<models::CommerceSubscriptionCreditResponse>>,
	/// Unified credits breakdown for this subscription item.
	#[serde(
		rename = "credits",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub credits: Option<Option<Box<models::CommerceCreditsResponse>>>,
	/// Unique identifier for the associated plan.
	#[serde(rename = "plan_id", deserialize_with = "Option::deserialize")]
	pub plan_id: Option<String>,
	/// Unique identifier for the associated price
	#[serde(rename = "price_id", skip_serializing_if = "Option::is_none")]
	pub price_id: Option<String>,
	/// The associated plan.
	#[serde(
		rename = "plan",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub plan: Option<Option<Box<models::CommercePlan>>>,
	/// The billing period for this subscription item.
	#[serde(rename = "plan_period")]
	pub plan_period: PlanPeriod,
	#[serde(rename = "payment_method", skip_serializing_if = "Option::is_none")]
	pub payment_method: Option<Box<models::CommercePaymentMethodResponse>>,
	#[serde(rename = "lifetime_paid", skip_serializing_if = "Option::is_none")]
	pub lifetime_paid: Option<Box<models::CommerceMoneyResponse>>,
	/// Information about the next payment.
	#[serde(
		rename = "next_payment",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub next_payment: Option<Option<Box<models::CommerceSubscriptionItemNextPaymentResponse>>>,
	/// Unique identifier for the payer.
	#[serde(rename = "payer_id")]
	pub payer_id: String,
	#[serde(rename = "payer", skip_serializing_if = "Option::is_none")]
	pub payer: Option<Box<models::CommercePayerResponse>>,
	/// Whether this subscription item includes a free trial.
	#[serde(rename = "is_free_trial")]
	pub is_free_trial: bool,
	/// Unix timestamp (in milliseconds) when the current period started.
	#[serde(rename = "period_start")]
	pub period_start: i64,
	/// Unix timestamp (in milliseconds) when the current period ends.
	#[serde(rename = "period_end", deserialize_with = "Option::deserialize")]
	pub period_end: Option<i64>,
	/// The day the subscription item was prorated from. Only available in some responses.
	#[serde(rename = "proration_date", skip_serializing_if = "Option::is_none")]
	pub proration_date: Option<String>,
	/// Unix timestamp (in milliseconds) when the subscription item was canceled.
	#[serde(rename = "canceled_at", deserialize_with = "Option::deserialize")]
	pub canceled_at: Option<i64>,
	/// Unix timestamp (in milliseconds) when the subscription item became past due.
	#[serde(rename = "past_due_at", deserialize_with = "Option::deserialize")]
	pub past_due_at: Option<i64>,
	/// Unix timestamp (in milliseconds) when the subscription item ended.
	#[serde(rename = "ended_at", deserialize_with = "Option::deserialize")]
	pub ended_at: Option<i64>,
	/// Unix timestamp (in milliseconds) when the subscription item was created.
	#[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
	pub created_at: Option<i64>,
	/// Unix timestamp (in milliseconds) when the subscription item was last updated.
	#[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
	pub updated_at: Option<i64>,
	/// Seat quantity for seat-based billing.
	#[serde(
		rename = "seats",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub seats: Option<Option<Box<models::CommerceSubscriptionItemSeatsResponse>>>,
	/// Totals for this subscription item.
	#[serde(
		rename = "totals",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub totals: Option<Option<Box<models::CommerceTotalsResponse2>>>,
}

impl CommerceSubscriptionItem {
	pub fn new(
		object: Object,
		id: String,
		instance_id: String,
		status: Status,
		plan_id: Option<String>,
		plan_period: PlanPeriod,
		payer_id: String,
		is_free_trial: bool,
		period_start: i64,
		period_end: Option<i64>,
		canceled_at: Option<i64>,
		past_due_at: Option<i64>,
		ended_at: Option<i64>,
	) -> CommerceSubscriptionItem {
		CommerceSubscriptionItem {
			object,
			id,
			instance_id,
			status,
			credit: None,
			credits: None,
			plan_id,
			price_id: None,
			plan: None,
			plan_period,
			payment_method: None,
			lifetime_paid: None,
			next_payment: None,
			payer_id,
			payer: None,
			is_free_trial,
			period_start,
			period_end,
			proration_date: None,
			canceled_at,
			past_due_at,
			ended_at,
			created_at: None,
			updated_at: None,
			seats: None,
			totals: None,
		}
	}
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "commerce_subscription_item")]
	CommerceSubscriptionItem,
}

impl Default for Object {
	fn default() -> Object {
		Self::CommerceSubscriptionItem
	}
}
/// Current status of the subscription item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
	#[serde(rename = "active")]
	Active,
	#[serde(rename = "canceled")]
	Canceled,
	#[serde(rename = "expired")]
	Expired,
	#[serde(rename = "ended")]
	Ended,
	#[serde(rename = "past_due")]
	PastDue,
	#[serde(rename = "upcoming")]
	Upcoming,
	#[serde(rename = "incomplete")]
	Incomplete,
	#[serde(rename = "abandoned")]
	Abandoned,
}

impl Default for Status {
	fn default() -> Status {
		Self::Active
	}
}
/// The billing period for this subscription item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlanPeriod {
	#[serde(rename = "month")]
	Month,
	#[serde(rename = "annual")]
	Annual,
}

impl Default for PlanPeriod {
	fn default() -> PlanPeriod {
		Self::Month
	}
}
