/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJwtTemplateRequest {
	/// JWT template name
	#[serde(rename = "name")]
	pub name: String,
	/// JWT template claims in JSON format
	#[serde(rename = "claims")]
	pub claims: serde_json::Value,
	/// JWT lifetime
	#[serde(
		rename = "lifetime",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub lifetime: Option<Option<u32>>,
	/// JWT allowed clock skew
	#[serde(
		rename = "allowed_clock_skew",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub allowed_clock_skew: Option<Option<u32>>,
	/// Whether a custom signing key/algorithm is also provided for this template
	#[serde(rename = "custom_signing_key", skip_serializing_if = "Option::is_none")]
	pub custom_signing_key: Option<bool>,
	/// The custom signing algorithm to use when minting JWTs. Required if `custom_signing_key` is `true`.
	#[serde(
		rename = "signing_algorithm",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub signing_algorithm: Option<Option<String>>,
	/// The custom signing private key to use when minting JWTs. Required if `custom_signing_key` is `true`.
	#[serde(
		rename = "signing_key",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub signing_key: Option<Option<String>>,
}

impl CreateJwtTemplateRequest {
	pub fn new(name: String, claims: serde_json::Value) -> CreateJwtTemplateRequest {
		CreateJwtTemplateRequest {
			name,
			claims,
			lifetime: None,
			allowed_clock_skew: None,
			custom_signing_key: None,
			signing_algorithm: None,
			signing_key: None,
		}
	}
}
