/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoleSetRequest {
	/// The name of the new role set
	#[serde(rename = "name")]
	pub name: String,
	/// A unique key for the role set. Must start with 'role_set:' and contain only lowercase alphanumeric characters and underscores. If not provided, a key will be generated from the name.
	#[serde(rename = "key", skip_serializing_if = "Option::is_none")]
	pub key: Option<String>,
	/// Optional description for the role set
	#[serde(
		rename = "description",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub description: Option<Option<String>>,
	/// The key of the role to use as the default role for new organization members. Must be one of the roles in the `roles` array.
	#[serde(rename = "default_role_key")]
	pub default_role_key: String,
	/// The key of the role to assign to organization creators. Must be one of the roles in the `roles` array.
	#[serde(rename = "creator_role_key")]
	pub creator_role_key: String,
	/// The type of the role set. \"initial\" role sets are the default for new organizations. Only one role set can be \"initial\" per instance.
	#[serde(rename = "type", skip_serializing_if = "Option::is_none")]
	pub r#type: Option<Type>,
	/// Array of role keys to include in the role set. Must contain at least one role and no more than 10 roles.
	#[serde(rename = "roles")]
	pub roles: Vec<String>,
}

impl CreateRoleSetRequest {
	pub fn new(name: String, default_role_key: String, creator_role_key: String, roles: Vec<String>) -> CreateRoleSetRequest {
		CreateRoleSetRequest {
			name,
			key: None,
			description: None,
			default_role_key,
			creator_role_key,
			r#type: None,
			roles,
		}
	}
}
/// The type of the role set. \"initial\" role sets are the default for new organizations. Only one role set can be \"initial\" per instance.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
	#[serde(rename = "initial")]
	Initial,
	#[serde(rename = "custom")]
	Custom,
}

impl Default for Type {
	fn default() -> Type {
		Self::Initial
	}
}
