/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateActorTokenRequest {
	/// The ID of the user being impersonated.
	#[serde(rename = "user_id")]
	pub user_id: String,
	#[serde(rename = "actor")]
	pub actor: models::CreateActorTokenRequestActor,
	/// Optional parameter to specify the life duration of the actor token in seconds. By default, the duration is 1 hour.
	#[serde(rename = "expires_in_seconds", skip_serializing_if = "Option::is_none")]
	pub expires_in_seconds: Option<i32>,
	/// The maximum duration that the session which will be created by the generated actor token should last. By default, the duration of a session created via an actor token, lasts 30 minutes.
	#[serde(rename = "session_max_duration_in_seconds", skip_serializing_if = "Option::is_none")]
	pub session_max_duration_in_seconds: Option<i32>,
}

impl CreateActorTokenRequest {
	pub fn new(user_id: String, actor: models::CreateActorTokenRequestActor) -> CreateActorTokenRequest {
		CreateActorTokenRequest {
			user_id,
			actor,
			expires_in_seconds: None,
			session_max_duration_in_seconds: None,
		}
	}
}
