/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBillingPriceRequest {
	/// The ID of the plan this price belongs to.
	#[serde(rename = "plan_id")]
	pub plan_id: String,
	/// The currency code (e.g., \"USD\"). Defaults to USD.
	#[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
	pub currency: Option<String>,
	/// The monthly amount in cents. Use `0` for a complimentary price. Positive amounts must be at least $1 (100 cents).
	#[serde(rename = "amount", deserialize_with = "Option::deserialize")]
	pub amount: Option<i64>,
	/// The monthly amount in cents when billed annually. Use `0` for a complimentary price. Positive amounts must be at least $1 (100 cents).
	#[serde(
		rename = "annual_monthly_amount",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub annual_monthly_amount: Option<Option<i64>>,
	/// An optional description for this custom price.
	#[serde(rename = "description", skip_serializing_if = "Option::is_none")]
	pub description: Option<String>,
	/// Which billing periods this price supports. Inferred from amounts if omitted.
	#[serde(rename = "supported_billing_periods", skip_serializing_if = "Option::is_none")]
	pub supported_billing_periods: Option<SupportedBillingPeriods>,
}

impl CreateBillingPriceRequest {
	pub fn new(plan_id: String, amount: Option<i64>) -> CreateBillingPriceRequest {
		CreateBillingPriceRequest {
			plan_id,
			currency: None,
			amount,
			annual_monthly_amount: None,
			description: None,
			supported_billing_periods: None,
		}
	}
}
/// Which billing periods this price supports. Inferred from amounts if omitted.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SupportedBillingPeriods {
	#[serde(rename = "month")]
	Month,
	#[serde(rename = "annual")]
	Annual,
	#[serde(rename = "both")]
	Both,
}

impl Default for SupportedBillingPeriods {
	fn default() -> SupportedBillingPeriods {
		Self::Month
	}
}
