/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateActorTokenRequestActor : The actor payload. It needs to include a sub property which should contain the ID of the actor. This whole payload will be also included in the JWT session token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateActorTokenRequestActor {
	/// The ID of the actor.
	#[serde(rename = "sub")]
	pub sub: String,
}

impl CreateActorTokenRequestActor {
	/// The actor payload. It needs to include a sub property which should contain the ID of the actor. This whole payload will be also included in the JWT session token.
	pub fn new(sub: String) -> CreateActorTokenRequestActor {
		CreateActorTokenRequestActor { sub }
	}
}
