/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationInvitationRequest {
	/// The email address of the new member that is going to be invited to the organization
	#[serde(rename = "email_address")]
	pub email_address: String,
	/// The ID of the user that invites the new member to the organization. Must be an administrator in the organization.
	#[serde(
		rename = "inviter_user_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub inviter_user_id: Option<Option<String>>,
	/// The role of the new member in the organization
	#[serde(rename = "role")]
	pub role: String,
	/// Metadata saved on the organization invitation, read-only from the Frontend API and fully accessible (read/write) from the Backend API. When the organization invitation is accepted, the metadata will be transferred to the newly created organization membership.
	#[serde(
		rename = "public_metadata",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub public_metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
	/// Metadata saved on the organization invitation, fully accessible (read/write) from the Backend API but not visible from the Frontend API. When the organization invitation is accepted, the metadata will be transferred to the newly created organization membership.
	#[serde(
		rename = "private_metadata",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub private_metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
	/// Optional URL that the invitee will be redirected to once they accept the invitation by clicking the join link in the invitation email.
	#[serde(
		rename = "redirect_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub redirect_url: Option<Option<String>>,
	/// The number of days the invitation will be valid for. By default, the invitation has a 30 days expire.
	#[serde(
		rename = "expires_in_days",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub expires_in_days: Option<Option<u32>>,
	/// Optional flag which denotes whether an email invitation should be sent to the given email address. Defaults to `true`.
	#[serde(
		rename = "notify",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub notify: Option<Option<bool>>,
}

impl CreateOrganizationInvitationRequest {
	pub fn new(email_address: String, role: String) -> CreateOrganizationInvitationRequest {
		CreateOrganizationInvitationRequest {
			email_address,
			inviter_user_id: None,
			role,
			public_metadata: None,
			private_metadata: None,
			redirect_url: None,
			expires_in_days: None,
			notify: None,
		}
	}
}
