/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateEnterpriseConnectionRequestOidc : OIDC connection-specific properties. Only applied when the enterprise connection uses OIDC (e.g. provider is oidc_custom, oidc_github_enterprise, or oidc_gitlab).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEnterpriseConnectionRequestOidc {
	/// OIDC client ID
	#[serde(
		rename = "client_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub client_id: Option<Option<String>>,
	/// OIDC client secret
	#[serde(
		rename = "client_secret",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub client_secret: Option<Option<String>>,
	/// OIDC discovery URL
	#[serde(
		rename = "discovery_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub discovery_url: Option<Option<String>>,
	/// OIDC authorization URL
	#[serde(
		rename = "auth_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub auth_url: Option<Option<String>>,
	/// OIDC token URL
	#[serde(
		rename = "token_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub token_url: Option<Option<String>>,
	/// OIDC userinfo URL
	#[serde(
		rename = "user_info_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub user_info_url: Option<Option<String>>,
	/// Whether PKCE is required (must be true for public clients with no client secret)
	#[serde(
		rename = "requires_pkce",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub requires_pkce: Option<Option<bool>>,
}

impl CreateEnterpriseConnectionRequestOidc {
	/// OIDC connection-specific properties. Only applied when the enterprise connection uses OIDC (e.g. provider is oidc_custom, oidc_github_enterprise, or oidc_gitlab).
	pub fn new() -> CreateEnterpriseConnectionRequestOidc {
		CreateEnterpriseConnectionRequestOidc {
			client_id: None,
			client_secret: None,
			discovery_url: None,
			auth_url: None,
			token_url: None,
			user_info_url: None,
			requires_pkce: None,
		}
	}
}
