/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAllowlistIdentifierRequest {
	/// The identifier to be added in the allow-list. This can be an email address, a phone number, or a web3 wallet.
	#[serde(rename = "identifier")]
	pub identifier: String,
	/// This flag denotes whether the given identifier will receive an invitation to join the application. Note that this only works for email address and phone number identifiers.
	#[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
	pub notify: Option<bool>,
}

impl CreateAllowlistIdentifierRequest {
	pub fn new(identifier: String) -> CreateAllowlistIdentifierRequest {
		CreateAllowlistIdentifierRequest { identifier, notify: None }
	}
}
