/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationMembershipRequest {
	/// The ID of the user that will be added as a member in the organization. The user needs to exist in the same instance as the organization and must not be a member of the given organization already.
	#[serde(rename = "user_id")]
	pub user_id: String,
	/// The role that the new member will have in the organization.
	#[serde(rename = "role")]
	pub role: String,
}

impl CreateOrganizationMembershipRequest {
	pub fn new(user_id: String, role: String) -> Result<CreateOrganizationMembershipRequest, &'static str> {
		// Validate user_id - must not be empty
		if user_id.trim().is_empty() {
			return Err("user_id cannot be empty");
		}

		// Validate role - must not be empty
		if role.trim().is_empty() {
			return Err("role cannot be empty");
		}

		Ok(CreateOrganizationMembershipRequest { user_id, role })
	}

	/// Creates a new instance without validation - use with caution
	pub fn new_unchecked(user_id: String, role: String) -> CreateOrganizationMembershipRequest {
		CreateOrganizationMembershipRequest { user_id, role }
	}

	/// Validates that the user_id and role meet requirements
	pub fn validate(&self) -> Result<(), &'static str> {
		// Validate user_id - must not be empty
		if self.user_id.trim().is_empty() {
			return Err("user_id cannot be empty");
		}

		// Validate role - must not be empty
		if self.role.trim().is_empty() {
			return Err("role cannot be empty");
		}

		Ok(())
	}
}
