/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSamlConnectionRequestAttributeMapping : Define the attribute name mapping between Identity Provider and Clerk's user properties
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSamlConnectionRequestAttributeMapping {
	#[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
	pub user_id: Option<String>,
	#[serde(rename = "email_address", skip_serializing_if = "Option::is_none")]
	pub email_address: Option<String>,
	#[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
	pub first_name: Option<String>,
	#[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
	pub last_name: Option<String>,
}

impl CreateSamlConnectionRequestAttributeMapping {
	/// Define the attribute name mapping between Identity Provider and Clerk's user properties
	pub fn new() -> CreateSamlConnectionRequestAttributeMapping {
		CreateSamlConnectionRequestAttributeMapping {
			user_id: None,
			email_address: None,
			first_name: None,
			last_name: None,
		}
	}
}
