/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateDemoInstance200Response {
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Object>,
    #[serde(rename = "frontend_api_key", skip_serializing_if = "Option::is_none")]
    pub frontend_api_key: Option<String>,
    #[serde(rename = "backend_api_key", skip_serializing_if = "Option::is_none")]
    pub backend_api_key: Option<String>,
    /// The public key that can be used to verify the session tokens of the created instance.
    #[serde(rename = "jwt_verification_key", skip_serializing_if = "Option::is_none")]
    pub jwt_verification_key: Option<String>,
    /// The URL of the hosted Accounts Portal of the created instance.
    #[serde(rename = "accounts_url", skip_serializing_if = "Option::is_none")]
    pub accounts_url: Option<String>,
}

impl CreateDemoInstance200Response {
    pub fn new() -> CreateDemoInstance200Response {
        CreateDemoInstance200Response {
            object: None,
            frontend_api_key: None,
            backend_api_key: None,
            jwt_verification_key: None,
            accounts_url: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "demo_dev_instance")]
    DemoDevInstance,
}

impl Default for Object {
    fn default() -> Object {
        Self::DemoDevInstance
    }
}

