/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAdminPortalLinkToken201Response {
	#[serde(rename = "object")]
	pub object: Object,
	#[serde(rename = "id")]
	pub id: String,
	/// The origin-level admin_portal_link this token was issued for.
	#[serde(rename = "admin_portal_link_id")]
	pub admin_portal_link_id: String,
	#[serde(rename = "instance_id")]
	pub instance_id: String,
	/// Optional. Present only when the link is scoped to an existing org.
	#[serde(rename = "organization_id", deserialize_with = "Option::deserialize")]
	pub organization_id: Option<String>,
	/// Optional opaque reference to the IT contact associated with this link.
	#[serde(rename = "it_contact_id", deserialize_with = "Option::deserialize")]
	pub it_contact_id: Option<String>,
	/// Caller-provided scopes for this token.
	#[serde(rename = "scopes", deserialize_with = "Option::deserialize")]
	pub scopes: Option<Vec<String>>,
	/// The single-use admin portal link token. Returned only on creation. URL-borne; treat as a secret.
	#[serde(rename = "token")]
	pub token: String,
	#[serde(rename = "revoked")]
	pub revoked: bool,
	#[serde(rename = "revocation_reason", deserialize_with = "Option::deserialize")]
	pub revocation_reason: Option<String>,
	#[serde(rename = "expired")]
	pub expired: bool,
	/// The timestamp for when the token will expire, in milliseconds.
	#[serde(rename = "expiration", deserialize_with = "Option::deserialize")]
	pub expiration: Option<f64>,
	/// The timestamp for when the token was created, in milliseconds.
	#[serde(rename = "created_at")]
	pub created_at: f64,
	/// The timestamp for when the token was last updated, in milliseconds.
	#[serde(rename = "updated_at")]
	pub updated_at: f64,
}

impl CreateAdminPortalLinkToken201Response {
	pub fn new(
		object: Object,
		id: String,
		admin_portal_link_id: String,
		instance_id: String,
		organization_id: Option<String>,
		it_contact_id: Option<String>,
		scopes: Option<Vec<String>>,
		token: String,
		revoked: bool,
		revocation_reason: Option<String>,
		expired: bool,
		expiration: Option<f64>,
		created_at: f64,
		updated_at: f64,
	) -> CreateAdminPortalLinkToken201Response {
		CreateAdminPortalLinkToken201Response {
			object,
			id,
			admin_portal_link_id,
			instance_id,
			organization_id,
			it_contact_id,
			scopes,
			token,
			revoked,
			revocation_reason,
			expired,
			expiration,
			created_at,
			updated_at,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "admin_portal_link_token")]
	AdminPortalLinkToken,
}

impl Default for Object {
	fn default() -> Object {
		Self::AdminPortalLinkToken
	}
}
