/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePhoneNumberRequest {
	/// The ID representing the user
	#[serde(rename = "user_id")]
	pub user_id: String,
	/// The new phone number. Must adhere to the E.164 standard for phone number format.
	#[serde(rename = "phone_number")]
	pub phone_number: String,
	/// When created, the phone number will be marked as verified.
	#[serde(
		rename = "verified",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub verified: Option<Option<bool>>,
	/// Create this phone number as the primary phone number for the user. Default: false, unless it is the first phone number.
	#[serde(
		rename = "primary",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub primary: Option<Option<bool>>,
	/// Create this phone number as reserved for multi-factor authentication. The phone number must also be verified. If there are no other reserved second factors, the phone number will be set as the default second factor.
	#[serde(
		rename = "reserved_for_second_factor",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub reserved_for_second_factor: Option<Option<bool>>,
}

impl CreatePhoneNumberRequest {
	pub fn new(user_id: String, phone_number: String) -> CreatePhoneNumberRequest {
		CreatePhoneNumberRequest {
			user_id,
			phone_number,
			verified: None,
			primary: None,
			reserved_for_second_factor: None,
		}
	}
}
