/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrganizationRequest {
	/// The name of the new organization. May not contain URLs or HTML. Max length: 256
	#[serde(rename = "name")]
	pub name: String,
	/// The ID of the User who will become the administrator for the new organization
	#[serde(
		rename = "created_by",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub created_by: Option<Option<String>>,
	/// Metadata saved on the organization, accessible only from the Backend API
	#[serde(
		rename = "private_metadata",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub private_metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
	/// Metadata saved on the organization, read-only from the Frontend API and fully accessible (read/write) from the Backend API
	#[serde(
		rename = "public_metadata",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub public_metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
	/// A slug for the new organization. Can contain only lowercase alphanumeric characters and the dash \"-\". Must be unique for the instance. This field should only be included when slugs are enabled in the organization settings, refer to our [documentation](https://clerk.com/docs/guides/organizations/overview#organization-slugs).
	#[serde(
		rename = "slug",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub slug: Option<Option<String>>,
	/// The maximum number of memberships allowed for this organization
	#[serde(
		rename = "max_allowed_memberships",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub max_allowed_memberships: Option<Option<u32>>,
	/// A custom date/time denoting _when_ the organization was created, specified in RFC3339 format (e.g. `2012-10-20T07:15:20.902Z`).
	#[serde(
		rename = "created_at",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub created_at: Option<Option<String>>,
	/// The key of the [role set](https://clerk.com/docs/guides/organizations/control-access/role-sets) to assign to this organization.
	#[serde(
		rename = "role_set_key",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub role_set_key: Option<Option<String>>,
}

impl CreateOrganizationRequest {
	pub fn new(name: String) -> CreateOrganizationRequest {
		CreateOrganizationRequest {
			name,
			created_by: None,
			private_metadata: None,
			public_metadata: None,
			slug: None,
			max_allowed_memberships: None,
			created_at: None,
			role_set_key: None,
		}
	}
}
