/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteMachine200Response {
	/// String representing the object's type.
	#[serde(rename = "object")]
	pub object: Object,
	/// The ID of the deleted machine
	#[serde(rename = "id")]
	pub id: String,
	/// Whether the machine was successfully deleted
	#[serde(rename = "deleted")]
	pub deleted: bool,
}

impl DeleteMachine200Response {
	pub fn new(object: Object, id: String, deleted: bool) -> DeleteMachine200Response {
		DeleteMachine200Response { object, id, deleted }
	}
}
/// String representing the object's type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "machine")]
	Machine,
}

impl Default for Object {
	fn default() -> Object {
		Self::Machine
	}
}
