/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DirectoryGroupRoleMapping : A mapping from a directory group to an organization role. Members of the group are assigned the role; the lowest-precedence match wins when a user belongs to multiple mapped groups.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectoryGroupRoleMapping {
	/// String representing the object's type. Always \"directory_group_role_mapping\".
	#[serde(rename = "object")]
	pub object: Object,
	/// Unique identifier for the directory group role mapping.
	#[serde(rename = "id")]
	pub id: String,
	/// The ID of the directory this mapping belongs to.
	#[serde(rename = "directory_id")]
	pub directory_id: String,
	/// The legacy name for `directory_id`. Carries the same value.
	#[serde(rename = "scim_directory_id")]
	pub scim_directory_id: String,
	/// The group ID from the identity provider.
	#[serde(rename = "directory_group_id")]
	pub directory_group_id: String,
	/// The legacy name for `directory_group_id`. Carries the same value.
	#[serde(rename = "scim_group_id")]
	pub scim_group_id: String,
	/// The display name of the group, as reported by the identity provider.
	#[serde(rename = "directory_group_display_name")]
	pub directory_group_display_name: String,
	/// The legacy name for `directory_group_display_name`. Carries the same value.
	#[serde(rename = "scim_group_display_name")]
	pub scim_group_display_name: String,
	#[serde(rename = "role", skip_serializing_if = "Option::is_none")]
	pub role: Option<Box<models::Role>>,
	/// Mapping precedence, starting at 1. Lower values take priority when a user belongs to multiple mapped groups.
	#[serde(rename = "precedence")]
	pub precedence: i32,
	/// Unix timestamp (milliseconds) of when the mapping was created.
	#[serde(rename = "created_at")]
	pub created_at: i64,
	/// Unix timestamp (milliseconds) of when the mapping was last updated.
	#[serde(rename = "updated_at")]
	pub updated_at: i64,
}

impl DirectoryGroupRoleMapping {
	/// A mapping from a directory group to an organization role. Members of the group are assigned the role; the lowest-precedence match wins when a user belongs to multiple mapped groups.
	pub fn new(
		object: Object,
		id: String,
		directory_id: String,
		scim_directory_id: String,
		directory_group_id: String,
		scim_group_id: String,
		directory_group_display_name: String,
		scim_group_display_name: String,
		precedence: i32,
		created_at: i64,
		updated_at: i64,
	) -> DirectoryGroupRoleMapping {
		DirectoryGroupRoleMapping {
			object,
			id,
			directory_id,
			scim_directory_id,
			directory_group_id,
			scim_group_id,
			directory_group_display_name,
			scim_group_display_name,
			role: None,
			precedence,
			created_at,
			updated_at,
		}
	}
}
/// String representing the object's type. Always \"directory_group_role_mapping\".
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "directory_group_role_mapping")]
	DirectoryGroupRoleMapping,
}

impl Default for Object {
	fn default() -> Object {
		Self::DirectoryGroupRoleMapping
	}
}
