/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EnterpriseConnectionOauthConfig : Present when the enterprise connection uses OIDC or EASIE
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnterpriseConnectionOauthConfig {
	/// OAuth config ID
	#[serde(rename = "id", skip_serializing_if = "Option::is_none")]
	pub id: Option<String>,
	/// Custom OIDC provider display name
	#[serde(rename = "name", skip_serializing_if = "Option::is_none")]
	pub name: Option<String>,
	/// OAuth provider key (e.g. oidc_custom, oidc_ghe_*, oidc_gitlab_ent_*)
	#[serde(rename = "provider_key", skip_serializing_if = "Option::is_none")]
	pub provider_key: Option<String>,
	/// OAuth client ID
	#[serde(
		rename = "client_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub client_id: Option<Option<String>>,
	/// OIDC discovery URL
	#[serde(
		rename = "discovery_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub discovery_url: Option<Option<String>>,
	/// OAuth authorization endpoint URL (present when configured or resolved from discovery)
	#[serde(
		rename = "auth_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub auth_url: Option<Option<String>>,
	/// OAuth token endpoint URL (present when configured or resolved from discovery)
	#[serde(
		rename = "token_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub token_url: Option<Option<String>>,
	/// OIDC userinfo endpoint URL (present when configured or resolved from discovery)
	#[serde(
		rename = "user_info_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub user_info_url: Option<Option<String>>,
	/// Whether PKCE is required for this OAuth client
	#[serde(rename = "requires_pkce", skip_serializing_if = "Option::is_none")]
	pub requires_pkce: Option<bool>,
	/// Logo URL for the provider
	#[serde(
		rename = "logo_public_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub logo_public_url: Option<Option<String>>,
	/// Unix timestamp in milliseconds when the config was created
	#[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
	pub created_at: Option<i64>,
	/// Unix timestamp in milliseconds when the config was last updated
	#[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
	pub updated_at: Option<i64>,
}

impl EnterpriseConnectionOauthConfig {
	/// Present when the enterprise connection uses OIDC or EASIE
	pub fn new() -> EnterpriseConnectionOauthConfig {
		EnterpriseConnectionOauthConfig {
			id: None,
			name: None,
			provider_key: None,
			client_id: None,
			discovery_url: None,
			auth_url: None,
			token_url: None,
			user_info_url: None,
			requires_pkce: None,
			logo_public_url: None,
			created_at: None,
			updated_at: None,
		}
	}
}
