/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnterpriseConnection {
	#[serde(rename = "object")]
	pub object: Object,
	/// The enterprise connection ID
	#[serde(rename = "id")]
	pub id: String,
	/// The display name of the connection
	#[serde(rename = "name")]
	pub name: String,
	#[serde(rename = "provider")]
	pub provider: String,
	#[serde(
		rename = "logo_public_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub logo_public_url: Option<Option<String>>,
	/// Whether the enterprise connection is active
	#[serde(rename = "active")]
	pub active: bool,
	/// Domains associated with the enterprise connection
	#[serde(rename = "domains")]
	pub domains: Vec<String>,
	/// Organization ID when the connection is linked to an organization
	#[serde(
		rename = "organization_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub organization_id: Option<Option<String>>,
	/// Controls whether to update the user's attributes on each sign-in
	#[serde(rename = "sync_user_attributes", skip_serializing_if = "Option::is_none")]
	pub sync_user_attributes: Option<bool>,
	/// When true, users cannot add additional identifications when using this connection
	#[serde(rename = "disable_additional_identifications", skip_serializing_if = "Option::is_none")]
	pub disable_additional_identifications: Option<bool>,
	/// Whether this connection supports account linking via organization membership
	#[serde(rename = "allow_organization_account_linking", skip_serializing_if = "Option::is_none")]
	pub allow_organization_account_linking: Option<bool>,
	/// Custom attributes to map from the IdP to the user's profile via SSO or SCIM provisioning
	#[serde(rename = "custom_attributes", skip_serializing_if = "Option::is_none")]
	pub custom_attributes: Option<Vec<models::EnterpriseConnectionCustomAttributesInner>>,
	#[serde(
		rename = "saml_connection",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub saml_connection: Option<Option<Box<models::EnterpriseConnectionSamlConnection>>>,
	#[serde(
		rename = "oauth_config",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub oauth_config: Option<Option<Box<models::EnterpriseConnectionOauthConfig>>>,
	/// Unix timestamp in milliseconds when the connection was created
	#[serde(rename = "created_at")]
	pub created_at: i64,
	/// Unix timestamp in milliseconds when the connection was last updated
	#[serde(rename = "updated_at")]
	pub updated_at: i64,
}

impl EnterpriseConnection {
	pub fn new(
		object: Object,
		id: String,
		name: String,
		provider: String,
		active: bool,
		domains: Vec<String>,
		created_at: i64,
		updated_at: i64,
	) -> EnterpriseConnection {
		EnterpriseConnection {
			object,
			id,
			name,
			provider,
			logo_public_url: None,
			active,
			domains,
			organization_id: None,
			sync_user_attributes: None,
			disable_additional_identifications: None,
			allow_organization_account_linking: None,
			custom_attributes: None,
			saml_connection: None,
			oauth_config: None,
			created_at,
			updated_at,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "enterprise_connection")]
	EnterpriseConnection,
}

impl Default for Object {
	fn default() -> Object {
		Self::EnterpriseConnection
	}
}
