/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnterpriseAccount {
	#[serde(rename = "id")]
	pub id: String,
	/// String representing the object's type. Objects of the same type share the same value.
	#[serde(rename = "object")]
	pub object: Object,
	/// The authentication protocol used to sign in.
	#[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
	pub protocol: Option<Protocol>,
	#[serde(rename = "provider")]
	pub provider: String,
	#[serde(rename = "active")]
	pub active: bool,
	#[serde(rename = "email_address")]
	pub email_address: String,
	#[serde(
		rename = "first_name",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub first_name: Option<Option<String>>,
	#[serde(
		rename = "last_name",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub last_name: Option<Option<String>>,
	/// The unique ID of the user in the external provider's system
	#[serde(
		rename = "provider_user_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub provider_user_id: Option<Option<String>>,
	#[serde(
		rename = "enterprise_connection_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub enterprise_connection_id: Option<Option<String>>,
	#[serde(rename = "public_metadata", skip_serializing_if = "Option::is_none")]
	pub public_metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
	#[serde(rename = "verification", deserialize_with = "Option::deserialize")]
	pub verification: Option<Box<models::EnterpriseAccountVerification>>,
	#[serde(
		rename = "enterprise_connection",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub enterprise_connection: Option<Option<Box<models::EnterpriseAccountConnection>>>,
	/// Unix timestamp of last authentication.
	#[serde(
		rename = "last_authenticated_at",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub last_authenticated_at: Option<Option<i64>>,
}

impl EnterpriseAccount {
	pub fn new(
		id: String,
		object: Object,
		provider: String,
		active: bool,
		email_address: String,
		verification: Option<models::EnterpriseAccountVerification>,
	) -> EnterpriseAccount {
		EnterpriseAccount {
			id,
			object,
			protocol: None,
			provider,
			active,
			email_address,
			first_name: None,
			last_name: None,
			provider_user_id: None,
			enterprise_connection_id: None,
			public_metadata: None,
			verification: if let Some(x) = verification { Some(Box::new(x)) } else { None },
			enterprise_connection: None,
			last_authenticated_at: None,
		}
	}
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "enterprise_account")]
	EnterpriseAccount,
}

impl Default for Object {
	fn default() -> Object {
		Self::EnterpriseAccount
	}
}
/// The authentication protocol used to sign in.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protocol {
	#[serde(rename = "oauth")]
	Oauth,
	#[serde(rename = "saml")]
	Saml,
}

impl Default for Protocol {
	fn default() -> Protocol {
		Self::Oauth
	}
}
