/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EnterpriseConnectionSamlConnectionLoginHint : Configuration for the login_hint sent to the IdP on SSO sign-in
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnterpriseConnectionSamlConnectionLoginHint {
	/// Controls the login_hint sent to the IdP on SSO sign-in
	#[serde(rename = "mode")]
	pub mode: Mode,
	/// The user public_metadata key whose value is sent as the login_hint when mode is custom_attribute
	#[serde(rename = "source", skip_serializing_if = "Option::is_none")]
	pub source: Option<String>,
}

impl EnterpriseConnectionSamlConnectionLoginHint {
	/// Configuration for the login_hint sent to the IdP on SSO sign-in
	pub fn new(mode: Mode) -> EnterpriseConnectionSamlConnectionLoginHint {
		EnterpriseConnectionSamlConnectionLoginHint { mode, source: None }
	}
}
/// Controls the login_hint sent to the IdP on SSO sign-in
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
	#[serde(rename = "email_address")]
	EmailAddress,
	#[serde(rename = "custom_attribute")]
	CustomAttribute,
	#[serde(rename = "off")]
	Off,
}

impl Default for Mode {
	fn default() -> Mode {
		Self::EmailAddress
	}
}
