/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EnterpriseConnectionSamlConnection : Present when the enterprise connection uses SAML
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnterpriseConnectionSamlConnection {
	/// SAML connection ID
	#[serde(rename = "id", skip_serializing_if = "Option::is_none")]
	pub id: Option<String>,
	/// SAML connection display name
	#[serde(rename = "name", skip_serializing_if = "Option::is_none")]
	pub name: Option<String>,
	/// IdP entity ID (optional, when connection details are loaded)
	#[serde(
		rename = "idp_entity_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub idp_entity_id: Option<Option<String>>,
	/// IdP SSO URL (optional, when connection details are loaded)
	#[serde(
		rename = "idp_sso_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub idp_sso_url: Option<Option<String>>,
	/// IdP metadata URL (optional, when connection details are loaded)
	#[serde(
		rename = "idp_metadata_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub idp_metadata_url: Option<Option<String>>,
	/// Assertion Consumer Service URL
	#[serde(
		rename = "acs_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub acs_url: Option<Option<String>>,
	/// Service Provider entity ID
	#[serde(
		rename = "sp_entity_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub sp_entity_id: Option<Option<String>>,
	/// Service Provider metadata URL
	#[serde(
		rename = "sp_metadata_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub sp_metadata_url: Option<Option<String>>,
	/// Whether the SAML connection is active
	#[serde(rename = "active", skip_serializing_if = "Option::is_none")]
	pub active: Option<bool>,
	/// Whether IdP-initiated SSO is allowed
	#[serde(rename = "allow_idp_initiated", skip_serializing_if = "Option::is_none")]
	pub allow_idp_initiated: Option<bool>,
	/// Whether subdomains are allowed for domain matching
	#[serde(rename = "allow_subdomains", skip_serializing_if = "Option::is_none")]
	pub allow_subdomains: Option<bool>,
	/// Whether to force re-authentication
	#[serde(rename = "force_authn", skip_serializing_if = "Option::is_none")]
	pub force_authn: Option<bool>,
	#[serde(rename = "login_hint", skip_serializing_if = "Option::is_none")]
	pub login_hint: Option<Box<models::EnterpriseConnectionSamlConnectionLoginHint>>,
}

impl EnterpriseConnectionSamlConnection {
	/// Present when the enterprise connection uses SAML
	pub fn new() -> EnterpriseConnectionSamlConnection {
		EnterpriseConnectionSamlConnection {
			id: None,
			name: None,
			idp_entity_id: None,
			idp_sso_url: None,
			idp_metadata_url: None,
			acs_url: None,
			sp_entity_id: None,
			sp_metadata_url: None,
			active: None,
			allow_idp_initiated: None,
			allow_subdomains: None,
			force_authn: None,
			login_hint: None,
		}
	}
}
