/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentificationLink {
	#[serde(rename = "type")]
	pub r#type: RHashType,
	#[serde(rename = "id")]
	pub id: String,
}

impl IdentificationLink {
	pub fn new(r#type: RHashType, id: String) -> IdentificationLink {
		IdentificationLink { r#type, id }
	}
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
	#[serde(rename = "oauth_google")]
	Google,
	#[serde(rename = "oauth_mock")]
	Mock,
}

impl Default for RHashType {
	fn default() -> RHashType {
		Self::Google
	}
}
