/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwksEcdsaPublicKey {
	#[serde(rename = "kid")]
	pub kid: String,
	#[serde(rename = "alg")]
	pub alg: String,
	#[serde(rename = "use")]
	pub r#use: String,
	#[serde(rename = "kty")]
	pub kty: Kty,
	#[serde(rename = "crv")]
	pub crv: String,
	#[serde(rename = "x")]
	pub x: String,
	#[serde(rename = "y")]
	pub y: String,
	#[serde(rename = "x5c", skip_serializing_if = "Option::is_none")]
	pub x5c: Option<Vec<String>>,
	#[serde(rename = "x5t", skip_serializing_if = "Option::is_none")]
	pub x5t: Option<String>,
	#[serde(rename = "x5t#S256", skip_serializing_if = "Option::is_none")]
	pub x5t_hash_s256: Option<String>,
	#[serde(rename = "x5u", skip_serializing_if = "Option::is_none")]
	pub x5u: Option<String>,
}

impl JwksEcdsaPublicKey {
	pub fn new(kid: String, alg: String, r#use: String, kty: Kty, crv: String, x: String, y: String) -> JwksEcdsaPublicKey {
		JwksEcdsaPublicKey {
			kid,
			alg,
			r#use,
			kty,
			crv,
			x,
			y,
			x5c: None,
			x5t: None,
			x5t_hash_s256: None,
			x5u: None,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kty {
	#[serde(rename = "EC")]
	Ec,
}

impl Default for Kty {
	fn default() -> Kty {
		Self::Ec
	}
}
