/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MachineWithoutScopedMachines {
	#[serde(rename = "object")]
	pub object: Object,
	/// Unique identifier for the machine.
	#[serde(rename = "id")]
	pub id: String,
	/// The name of the machine.
	#[serde(rename = "name")]
	pub name: String,
	/// The ID of the instance this machine belongs to.
	#[serde(rename = "instance_id")]
	pub instance_id: String,
	/// Unix timestamp of creation.
	#[serde(rename = "created_at")]
	pub created_at: i64,
	/// Unix timestamp of last update.
	#[serde(rename = "updated_at")]
	pub updated_at: i64,
	/// The default time-to-live (TTL) in seconds for tokens created by this machine.
	#[serde(rename = "default_token_ttl", skip_serializing_if = "Option::is_none")]
	pub default_token_ttl: Option<u32>,
}

impl MachineWithoutScopedMachines {
	pub fn new(object: Object, id: String, name: String, instance_id: String, created_at: i64, updated_at: i64) -> MachineWithoutScopedMachines {
		MachineWithoutScopedMachines {
			object,
			id,
			name,
			instance_id,
			created_at,
			updated_at,
			default_token_ttl: None,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "machine")]
	Machine,
}

impl Default for Object {
	fn default() -> Object {
		Self::Machine
	}
}
