/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthApplication {
	#[serde(rename = "object")]
	pub object: Object,
	#[serde(rename = "id")]
	pub id: String,
	#[serde(rename = "instance_id")]
	pub instance_id: String,
	#[serde(rename = "name")]
	pub name: String,
	#[serde(rename = "client_id")]
	pub client_id: String,
	#[serde(rename = "client_uri", deserialize_with = "Option::deserialize")]
	pub client_uri: Option<String>,
	#[serde(rename = "client_image_url", deserialize_with = "Option::deserialize")]
	pub client_image_url: Option<String>,
	#[serde(rename = "dynamically_registered")]
	pub dynamically_registered: bool,
	#[serde(rename = "consent_screen_enabled")]
	pub consent_screen_enabled: bool,
	#[serde(rename = "pkce_required")]
	pub pkce_required: bool,
	#[serde(rename = "public")]
	pub public: bool,
	#[serde(rename = "scopes")]
	pub scopes: String,
	#[serde(rename = "redirect_uris")]
	pub redirect_uris: Vec<String>,
	/// Deprecated: Use redirect_uris instead.
	#[serde(rename = "callback_url")]
	pub callback_url: String,
	#[serde(rename = "authorize_url")]
	pub authorize_url: String,
	#[serde(rename = "token_fetch_url")]
	pub token_fetch_url: String,
	#[serde(rename = "user_info_url")]
	pub user_info_url: String,
	#[serde(rename = "discovery_url")]
	pub discovery_url: String,
	#[serde(rename = "token_introspection_url")]
	pub token_introspection_url: String,
	/// Unix timestamp of creation.
	#[serde(rename = "created_at")]
	pub created_at: i64,
	/// Unix timestamp of last update.
	#[serde(rename = "updated_at")]
	pub updated_at: i64,
}

impl OAuthApplication {
	pub fn new(
		object: Object,
		id: String,
		instance_id: String,
		name: String,
		client_id: String,
		client_uri: Option<String>,
		client_image_url: Option<String>,
		dynamically_registered: bool,
		consent_screen_enabled: bool,
		pkce_required: bool,
		public: bool,
		scopes: String,
		redirect_uris: Vec<String>,
		callback_url: String,
		authorize_url: String,
		token_fetch_url: String,
		user_info_url: String,
		discovery_url: String,
		token_introspection_url: String,
		created_at: i64,
		updated_at: i64,
	) -> OAuthApplication {
		OAuthApplication {
			object,
			id,
			instance_id,
			name,
			client_id,
			client_uri,
			client_image_url,
			dynamically_registered,
			consent_screen_enabled,
			pkce_required,
			public,
			scopes,
			redirect_uris,
			callback_url,
			authorize_url,
			token_fetch_url,
			user_info_url,
			discovery_url,
			token_introspection_url,
			created_at,
			updated_at,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "oauth_application")]
	OauthApplication,
}

impl Default for Object {
	fn default() -> Object {
		Self::OauthApplication
	}
}
