/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrganizationDomainVerification : The verification object from an organization domain
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationDomainVerification {
	/// Status of the verification. It can be `unverified`, `verified`, `failed`, or `expired`.
	#[serde(rename = "status")]
	pub status: String,
	/// Name of the strategy used to verify the domain
	#[serde(rename = "strategy")]
	pub strategy: String,
	/// How many attempts have been made to verify the domain
	#[serde(rename = "attempts", deserialize_with = "Option::deserialize")]
	pub attempts: Option<i32>,
	/// Unix timestamp of when the verification will expire
	#[serde(rename = "expire_at", deserialize_with = "Option::deserialize")]
	pub expire_at: Option<i64>,
	/// Unix timestamp of when ownership was verified. Only populated on `ownership_verification`; null on `affiliation_verification`.
	#[serde(rename = "verified_at", deserialize_with = "Option::deserialize")]
	pub verified_at: Option<i64>,
}

impl OrganizationDomainVerification {
	/// The verification object from an organization domain
	pub fn new(
		status: String,
		strategy: String,
		attempts: Option<i32>,
		expire_at: Option<i64>,
		verified_at: Option<i64>,
	) -> OrganizationDomainVerification {
		OrganizationDomainVerification {
			status,
			strategy,
			attempts,
			expire_at,
			verified_at,
		}
	}
}
