/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrganizationDomain : An organization domain
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationDomain {
	/// String representing the object's type. Objects of the same type share the same value. Always `organization_domain`
	#[serde(rename = "object")]
	pub object: Object,
	/// Unique identifier for the organization domain
	#[serde(rename = "id")]
	pub id: String,
	/// Unique identifier for the organization
	#[serde(rename = "organization_id")]
	pub organization_id: String,
	/// Name of the organization domain
	#[serde(rename = "name")]
	pub name: String,
	/// Mode of enrollment for the domain
	#[serde(rename = "enrollment_mode")]
	pub enrollment_mode: EnrollmentMode,
	/// Affiliation email address for the domain, if available.
	#[serde(rename = "affiliation_email_address", deserialize_with = "Option::deserialize")]
	pub affiliation_email_address: Option<String>,
	/// Verification details for the user-facing affiliation between the domain and the organization (e.g. affiliation_email_code).
	#[serde(rename = "affiliation_verification", deserialize_with = "Option::deserialize")]
	pub affiliation_verification: Option<Box<models::OrganizationDomainVerification>>,
	/// Verification details for the underlying DNS domain ownership proof (TXT challenge or dashboard override). Null until ownership has been attempted.
	#[serde(rename = "ownership_verification", deserialize_with = "Option::deserialize")]
	pub ownership_verification: Option<Box<models::OrganizationDomainVerification>>,
	/// Deprecated alias for `affiliation_verification`. Kept for backward compatibility on the current API version; will be removed in the next API version. Prefer `affiliation_verification`.
	#[serde(rename = "verification", deserialize_with = "Option::deserialize")]
	pub verification: Option<Box<models::OrganizationDomainVerification>>,
	/// Total number of pending invitations associated with this domain
	#[serde(rename = "total_pending_invitations")]
	pub total_pending_invitations: i32,
	/// Total number of pending suggestions associated with this domain
	#[serde(rename = "total_pending_suggestions")]
	pub total_pending_suggestions: i32,
	/// Public organization data associated with this domain
	#[serde(
		rename = "public_organization_data",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub public_organization_data: Option<Option<Box<models::OrganizationInvitationPublicOrganizationData>>>,
	/// Unix timestamp when the domain was created
	#[serde(rename = "created_at")]
	pub created_at: i64,
	/// Unix timestamp of the last update to the domain
	#[serde(rename = "updated_at")]
	pub updated_at: i64,
}

impl OrganizationDomain {
	/// An organization domain
	pub fn new(
		object: Object,
		id: String,
		organization_id: String,
		name: String,
		enrollment_mode: EnrollmentMode,
		affiliation_email_address: Option<String>,
		affiliation_verification: Option<models::OrganizationDomainVerification>,
		ownership_verification: Option<models::OrganizationDomainVerification>,
		verification: Option<models::OrganizationDomainVerification>,
		total_pending_invitations: i32,
		total_pending_suggestions: i32,
		created_at: i64,
		updated_at: i64,
	) -> OrganizationDomain {
		OrganizationDomain {
			object,
			id,
			organization_id,
			name,
			enrollment_mode,
			affiliation_email_address,
			affiliation_verification: if let Some(x) = affiliation_verification {
				Some(Box::new(x))
			} else {
				None
			},
			ownership_verification: if let Some(x) = ownership_verification { Some(Box::new(x)) } else { None },
			verification: if let Some(x) = verification { Some(Box::new(x)) } else { None },
			total_pending_invitations,
			total_pending_suggestions,
			public_organization_data: None,
			created_at,
			updated_at,
		}
	}
}
/// String representing the object's type. Objects of the same type share the same value. Always `organization_domain`
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "organization_domain")]
	OrganizationDomain,
}

impl Default for Object {
	fn default() -> Object {
		Self::OrganizationDomain
	}
}
/// Mode of enrollment for the domain
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnrollmentMode {
	#[serde(rename = "manual_invitation")]
	ManualInvitation,
	#[serde(rename = "automatic_invitation")]
	AutomaticInvitation,
	#[serde(rename = "automatic_suggestion")]
	AutomaticSuggestion,
	#[serde(rename = "enterprise_sso")]
	EnterpriseSso,
}

impl Default for EnrollmentMode {
	fn default() -> EnrollmentMode {
		Self::ManualInvitation
	}
}
