/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganizationInvitationPublicOrganizationData {
	#[serde(rename = "id")]
	pub id: String,
	#[serde(rename = "name")]
	pub name: String,
	#[serde(rename = "slug")]
	pub slug: String,
	#[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
	pub image_url: Option<String>,
	#[serde(rename = "has_image")]
	pub has_image: bool,
}

impl OrganizationInvitationPublicOrganizationData {
	pub fn new(id: String, name: String, slug: String, has_image: bool) -> OrganizationInvitationPublicOrganizationData {
		OrganizationInvitationPublicOrganizationData {
			id,
			name,
			slug,
			image_url: None,
			has_image,
		}
	}
}
