/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Passkey {
	#[serde(rename = "id", skip_serializing_if = "Option::is_none")]
	pub id: Option<String>,
	/// String representing the object's type. Objects of the same type share the same value.
	#[serde(rename = "object")]
	pub object: Object,
	#[serde(rename = "name")]
	pub name: String,
	/// Unix timestamp of when the passkey was last used.
	#[serde(rename = "last_used_at")]
	pub last_used_at: i64,
	#[serde(rename = "verification", deserialize_with = "Option::deserialize")]
	pub verification: Option<Box<models::VerificationPasskey>>,
}

impl Passkey {
	pub fn new(object: Object, name: String, last_used_at: i64, verification: Option<models::VerificationPasskey>) -> Passkey {
		Passkey {
			id: None,
			object,
			name,
			last_used_at,
			verification: if let Some(x) = verification { Some(Box::new(x)) } else { None },
		}
	}
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "passkey")]
	Passkey,
}

impl Default for Object {
	fn default() -> Object {
		Self::Passkey
	}
}
