/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrepareEmailAddressVerification200Response {
	/// The type of the verification object.
	#[serde(rename = "object", skip_serializing_if = "Option::is_none")]
	pub object: Option<String>,
	/// The ID of the verification. Pass this to attempt_verification.
	#[serde(rename = "id", skip_serializing_if = "Option::is_none")]
	pub id: Option<String>,
	/// The status of the verification (unverified, verified, expired, or failed).
	#[serde(rename = "status", skip_serializing_if = "Option::is_none")]
	pub status: Option<String>,
	/// The verification strategy (email_code or phone_code).
	#[serde(rename = "strategy", skip_serializing_if = "Option::is_none")]
	pub strategy: Option<String>,
	/// The number of attempts made against this verification.
	#[serde(
		rename = "attempts",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub attempts: Option<Option<i32>>,
	/// Unix timestamp (milliseconds) at which the code expires.
	#[serde(
		rename = "expire_at",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub expire_at: Option<Option<i64>>,
	/// The channel the code was sent over (phone numbers only).
	#[serde(
		rename = "channel",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub channel: Option<Option<String>>,
}

impl PrepareEmailAddressVerification200Response {
	pub fn new() -> PrepareEmailAddressVerification200Response {
		PrepareEmailAddressVerification200Response {
			object: None,
			id: None,
			status: None,
			strategy: None,
			attempts: None,
			expire_at: None,
			channel: None,
		}
	}
}
