/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshSessionRequest {
	/// The JWT that is sent via the `__session` cookie from your frontend. Note: this JWT must be associated with the supplied session ID.
	#[serde(rename = "expired_token")]
	pub expired_token: String,
	/// The refresh token from the `__refresh` cookie set via FAPI's handshake flow.
	#[serde(rename = "refresh_token")]
	pub refresh_token: String,
	/// The origin of the request.
	#[serde(rename = "request_origin")]
	pub request_origin: String,
	/// The headers of the request.
	#[serde(
		rename = "request_headers",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub request_headers: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
	/// The format of the response.
	#[serde(
		rename = "format",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub format: Option<Option<Format>>,
	/// The IP address of the request.
	#[serde(
		rename = "request_originating_ip",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub request_originating_ip: Option<Option<String>>,
}

impl RefreshSessionRequest {
	pub fn new(expired_token: String, refresh_token: String, request_origin: String) -> RefreshSessionRequest {
		RefreshSessionRequest {
			expired_token,
			refresh_token,
			request_origin,
			request_headers: None,
			format: None,
			request_originating_ip: None,
		}
	}
}
/// The format of the response.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
	#[serde(rename = "token")]
	Token,
	#[serde(rename = "cookie")]
	Cookie,
}

impl Default for Format {
	fn default() -> Format {
		Self::Token
	}
}
