/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceUserPhoneNumberRequest {
	/// The new phone number. Must adhere to the E.164 standard for phone number format.
	#[serde(rename = "phone_number")]
	pub phone_number: String,
	/// Controls the status of the replacement phone number. Defaults to `verified`. Set to `reserved` to create it reserved (unverified but usable for sign-in and locked so no other user can claim it), or to `unverified` to create it neither usable for sign-in nor locked.  **Warning:** `unverified` can lock the user out of their account. An unverified phone number cannot be used to sign in, so if the user has no other verified or reserved identifier, they will be unable to authenticate and unable to verify this number. Prefer `reserved` unless you specifically need the number left unclaimed — for example so that another user can also hold it until one of them verifies it.
	#[serde(rename = "identification_status", skip_serializing_if = "Option::is_none")]
	pub identification_status: Option<IdentificationStatus>,
}

impl ReplaceUserPhoneNumberRequest {
	pub fn new(phone_number: String) -> ReplaceUserPhoneNumberRequest {
		ReplaceUserPhoneNumberRequest {
			phone_number,
			identification_status: None,
		}
	}
}
/// Controls the status of the replacement phone number. Defaults to `verified`. Set to `reserved` to create it reserved (unverified but usable for sign-in and locked so no other user can claim it), or to `unverified` to create it neither usable for sign-in nor locked.  **Warning:** `unverified` can lock the user out of their account. An unverified phone number cannot be used to sign in, so if the user has no other verified or reserved identifier, they will be unable to authenticate and unable to verify this number. Prefer `reserved` unless you specifically need the number left unclaimed — for example so that another user can also hold it until one of them verifies it.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IdentificationStatus {
	#[serde(rename = "verified")]
	Verified,
	#[serde(rename = "reserved")]
	Reserved,
	#[serde(rename = "unverified")]
	Unverified,
}

impl Default for IdentificationStatus {
	fn default() -> IdentificationStatus {
		Self::Verified
	}
}
