/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokeOrganizationInvitationRequest {
	/// The ID of the user that revokes the invitation. Must be an administrator in the organization.
	#[serde(
		rename = "requesting_user_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub requesting_user_id: Option<Option<String>>,
}

impl RevokeOrganizationInvitationRequest {
	pub fn new() -> RevokeOrganizationInvitationRequest {
		RevokeOrganizationInvitationRequest { requesting_user_id: None }
	}
}
