/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoleSetItem : A role within a role set
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleSetItem {
	#[serde(rename = "object")]
	pub object: Object,
	/// The unique identifier of the role
	#[serde(rename = "id")]
	pub id: String,
	/// The name of the role
	#[serde(rename = "name")]
	pub name: String,
	/// The key of the role (e.g., \"org:admin\", \"org:member\")
	#[serde(rename = "key")]
	pub key: String,
	/// Optional description of the role
	#[serde(rename = "description", deserialize_with = "Option::deserialize")]
	pub description: Option<String>,
	/// The number of members assigned to this role within the role set
	#[serde(
		rename = "members_count",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub members_count: Option<Option<i64>>,
	/// Whether this role has any members assigned within the role set
	#[serde(
		rename = "has_members",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub has_members: Option<Option<bool>>,
	/// Unix timestamp of role creation
	#[serde(rename = "created_at")]
	pub created_at: i64,
	/// Unix timestamp of last role update
	#[serde(rename = "updated_at")]
	pub updated_at: i64,
}

impl RoleSetItem {
	/// A role within a role set
	pub fn new(object: Object, id: String, name: String, key: String, description: Option<String>, created_at: i64, updated_at: i64) -> RoleSetItem {
		RoleSetItem {
			object,
			id,
			name,
			key,
			description,
			members_count: None,
			has_members: None,
			created_at,
			updated_at,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "role_set_item")]
	RoleSetItem,
}

impl Default for Object {
	fn default() -> Object {
		Self::RoleSetItem
	}
}
