/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RoleSet : A role set defines a collection of roles that can be assigned to organization members
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleSet {
	#[serde(rename = "object")]
	pub object: Object,
	/// The unique identifier of the role set
	#[serde(rename = "id")]
	pub id: String,
	/// The name of the role set
	#[serde(rename = "name")]
	pub name: String,
	/// A unique key for the role set (e.g., \"role_set:default\")
	#[serde(rename = "key")]
	pub key: String,
	/// Optional description of the role set
	#[serde(rename = "description", deserialize_with = "Option::deserialize")]
	pub description: Option<String>,
	/// The list of roles in this role set
	#[serde(rename = "roles")]
	pub roles: Vec<models::RoleSetItem>,
	/// The default role assigned to new organization members
	#[serde(
		rename = "default_role",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub default_role: Option<Option<Box<models::RoleSetItem>>>,
	/// The role assigned to the creator of an organization
	#[serde(
		rename = "creator_role",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub creator_role: Option<Option<Box<models::RoleSetItem>>>,
	/// The type of the role set (\"initial\" or \"custom\")
	#[serde(rename = "type")]
	pub r#type: Type,
	/// Active migration information, only present when status is \"enqueued\" or \"in_progress\"
	#[serde(
		rename = "role_set_migration",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub role_set_migration: Option<Option<Box<models::RoleSetMigration>>>,
	/// Unix timestamp of role set creation
	#[serde(rename = "created_at")]
	pub created_at: i64,
	/// Unix timestamp of last role set update
	#[serde(rename = "updated_at")]
	pub updated_at: i64,
}

impl RoleSet {
	/// A role set defines a collection of roles that can be assigned to organization members
	pub fn new(
		object: Object,
		id: String,
		name: String,
		key: String,
		description: Option<String>,
		roles: Vec<models::RoleSetItem>,
		r#type: Type,
		created_at: i64,
		updated_at: i64,
	) -> RoleSet {
		RoleSet {
			object,
			id,
			name,
			key,
			description,
			roles,
			default_role: None,
			creator_role: None,
			r#type,
			role_set_migration: None,
			created_at,
			updated_at,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "role_set")]
	RoleSet,
}

impl Default for Object {
	fn default() -> Object {
		Self::RoleSet
	}
}
/// The type of the role set (\"initial\" or \"custom\")
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
	#[serde(rename = "initial")]
	Initial,
	#[serde(rename = "custom")]
	Custom,
}

impl Default for Type {
	fn default() -> Type {
		Self::Initial
	}
}
