/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetUserPasswordCompromisedRequest {
	#[serde(
		rename = "revoke_all_sessions",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub revoke_all_sessions: Option<Option<bool>>,
}

impl SetUserPasswordCompromisedRequest {
	pub fn new() -> SetUserPasswordCompromisedRequest {
		SetUserPasswordCompromisedRequest { revoke_all_sessions: None }
	}
}
