/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignUpVerification {
	#[serde(rename = "next_action", skip_serializing_if = "Option::is_none")]
	pub next_action: Option<NextAction>,
	#[serde(rename = "supported_strategies", skip_serializing_if = "Option::is_none")]
	pub supported_strategies: Option<Vec<String>>,
}

impl SignUpVerification {
	pub fn new() -> SignUpVerification {
		SignUpVerification {
			next_action: None,
			supported_strategies: None,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NextAction {
	#[serde(rename = "needs_prepare")]
	NeedsPrepare,
	#[serde(rename = "needs_attempt")]
	NeedsAttempt,
	#[serde(rename = "")]
	Empty,
}

impl Default for NextAction {
	fn default() -> NextAction {
		Self::NeedsPrepare
	}
}
