/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SvixUrl {
    #[serde(rename = "svix_url")]
    pub svix_url: String,
}

impl SvixUrl {
    pub fn new(svix_url: String) -> SvixUrl {
        SvixUrl {
            svix_url,
        }
    }
}


