/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserRequest {
	/// The ID of the user as used in your external systems or your previous authentication solution. Must be unique across your instance.
	#[serde(
		rename = "external_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub external_id: Option<Option<String>>,
	/// The first name to assign to the user
	#[serde(
		rename = "first_name",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub first_name: Option<Option<String>>,
	/// The last name to assign to the user
	#[serde(
		rename = "last_name",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub last_name: Option<Option<String>>,
	/// The locale to assign to the user (e.g., \"en-US\", \"fr-FR\")
	#[serde(
		rename = "locale",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub locale: Option<Option<String>>,
	/// The ID of the email address to set as primary. It must be verified, and present on the current user.
	#[serde(
		rename = "primary_email_address_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub primary_email_address_id: Option<Option<String>>,
	/// If set to `true`, the user will be notified that their primary email address has changed. By default, no notification is sent.
	#[serde(
		rename = "notify_primary_email_address_changed",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub notify_primary_email_address_changed: Option<Option<bool>>,
	/// The ID of the phone number to set as primary. It must be verified, and present on the current user.
	#[serde(
		rename = "primary_phone_number_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub primary_phone_number_id: Option<Option<String>>,
	/// The ID of the web3 wallets to set as primary. It must be verified, and present on the current user.
	#[serde(
		rename = "primary_web3_wallet_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub primary_web3_wallet_id: Option<Option<String>>,
	/// The username to give to the user. It must be unique across your instance.
	#[serde(
		rename = "username",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub username: Option<Option<String>>,
	/// The ID of the image to set as the user's profile image
	#[serde(
		rename = "profile_image_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub profile_image_id: Option<Option<String>>,
	/// The plaintext password to give the user. Must be at least 8 characters long, and cannot be in any list of hacked passwords.
	#[serde(
		rename = "password",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub password: Option<Option<String>>,
	/// In case you already have the password digests and not the passwords, you can use them for the newly created user via this property. The digests should be generated with one of the supported algorithms. The hashing algorithm can be specified using the `password_hasher` property.
	#[serde(rename = "password_digest", skip_serializing_if = "Option::is_none")]
	pub password_digest: Option<String>,
	/// The hashing algorithm that was used to generate the password digest.  The algorithms we support at the moment are [`bcrypt`](https://en.wikipedia.org/wiki/Bcrypt), [`bcrypt_sha256_django`](https://docs.djangoproject.com/en/4.0/topics/auth/passwords/), [`md5`](https://en.wikipedia.org/wiki/MD5), `pbkdf2_sha1`, `pbkdf2_sha256`, [`pbkdf2_sha256_django`](https://docs.djangoproject.com/en/4.0/topics/auth/passwords/), `pbkdf2_sha512`, [`phpass`](https://www.openwall.com/phpass/), `md5_phpass`, [`scrypt_firebase`](https://firebaseopensource.com/projects/firebase/scrypt/), [`scrypt_werkzeug`](https://werkzeug.palletsprojects.com/en/3.0.x/utils/#werkzeug.security.generate_password_hash), [`sha256`](https://en.wikipedia.org/wiki/SHA-2), [`ldap_ssha`](https://www.openldap.org/faq/data/cache/347.html), the [`argon2`](https://argon2.online/) variants: `argon2i` and `argon2id`, `sha512_symfony`, the SHA-512 variant of the [Symfony](https://symfony.com/doc/current/security/passwords.html) legacy hasher, and `pbkdf2_sha512_hex`, a variant of `pbkdf2_sha512` that accepts hex-encoded salt and hash.  Each of the supported hashers expects the incoming digest to be in a particular format. See the [Clerk docs](https://clerk.com/docs/references/backend/user/create-user) for more information.
	#[serde(rename = "password_hasher", skip_serializing_if = "Option::is_none")]
	pub password_hasher: Option<String>,
	/// Set it to `true` if you're updating the user's password and want to skip any password policy settings check. This parameter can only be used when providing a `password`.
	#[serde(
		rename = "skip_password_checks",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub skip_password_checks: Option<Option<bool>>,
	/// Set to `true` to sign out the user from all their active sessions once their password is updated. This parameter can only be used when providing a `password`.
	#[serde(
		rename = "sign_out_of_other_sessions",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub sign_out_of_other_sessions: Option<Option<bool>>,
	/// In case TOTP is configured on the instance, you can provide the secret to enable it on the specific user without the need to reset it.
	#[serde(
		rename = "totp_secret",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub totp_secret: Option<Option<String>>,
	/// If Backup Codes are configured on the instance, you can provide them to enable it on the specific user without the need to reset them.
	#[serde(rename = "backup_codes", skip_serializing_if = "Option::is_none")]
	pub backup_codes: Option<Vec<String>>,
	/// If true, the user can delete themselves with the Frontend API.
	#[serde(
		rename = "delete_self_enabled",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub delete_self_enabled: Option<Option<bool>>,
	/// If true, the user can create organizations with the Frontend API.
	#[serde(
		rename = "create_organization_enabled",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub create_organization_enabled: Option<Option<bool>>,
	/// A custom timestamp denoting _when_ the user accepted legal requirements, specified in RFC3339 format.
	#[serde(
		rename = "legal_accepted_at",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub legal_accepted_at: Option<Option<String>>,
	/// When set to `true` all legal checks are skipped.
	#[serde(
		rename = "skip_legal_checks",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub skip_legal_checks: Option<Option<bool>>,
	/// The maximum number of organizations the user can create. 0 means unlimited.
	#[serde(
		rename = "create_organizations_limit",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub create_organizations_limit: Option<Option<i32>>,
	/// A custom date/time denoting _when_ the user signed up to the application.
	#[serde(
		rename = "created_at",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub created_at: Option<Option<String>>,
	/// When set to `true`, the user will bypass Device Trust checks during sign-in.
	#[serde(
		rename = "bypass_client_trust",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub bypass_client_trust: Option<Option<bool>>,
}

impl UpdateUserRequest {
	pub fn new() -> UpdateUserRequest {
		UpdateUserRequest {
			external_id: None,
			first_name: None,
			last_name: None,
			locale: None,
			primary_email_address_id: None,
			notify_primary_email_address_changed: None,
			primary_phone_number_id: None,
			primary_web3_wallet_id: None,
			username: None,
			profile_image_id: None,
			password: None,
			password_digest: None,
			password_hasher: None,
			skip_password_checks: None,
			sign_out_of_other_sessions: None,
			totp_secret: None,
			backup_codes: None,
			delete_self_enabled: None,
			create_organization_enabled: None,
			legal_accepted_at: None,
			skip_legal_checks: None,
			create_organizations_limit: None,
			created_at: None,
			bypass_client_trust: None,
		}
	}
}
