/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateInstanceOrganizationSettingsRequest {
	#[serde(
		rename = "enabled",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub enabled: Option<Option<bool>>,
	#[serde(
		rename = "max_allowed_memberships",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub max_allowed_memberships: Option<Option<i32>>,
}

impl UpdateInstanceOrganizationSettingsRequest {
	pub fn new() -> UpdateInstanceOrganizationSettingsRequest {
		UpdateInstanceOrganizationSettingsRequest {
			enabled: None,
			max_allowed_memberships: None,
		}
	}
}
