/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateInstanceRequest {
	/// Toggles test mode for this instance, allowing the use of test email addresses and phone numbers. Defaults to true for development instances.
	#[serde(
		rename = "test_mode",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub test_mode: Option<Option<bool>>,
	/// Whether the instance should be using the HIBP service to check passwords for breaches
	#[serde(
		rename = "hibp",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub hibp: Option<Option<bool>>,
	#[serde(
		rename = "support_email",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub support_email: Option<Option<String>>,
	#[serde(
		rename = "clerk_js_version",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub clerk_js_version: Option<Option<String>>,
	#[serde(
		rename = "development_origin",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub development_origin: Option<Option<String>>,
	/// For browser-like stacks such as browser extensions, Electron (not officially supported), or Capacitor.js (not officially supported), the instance allowed origins need to be updated with the request origin value. For Chrome extensions popup, background, or service worker pages, the origin is chrome-extension://extension_uuid. For Electron apps the default origin is http://localhost:3000. For Capacitor, the origin is capacitor://localhost.
	#[serde(rename = "allowed_origins", skip_serializing_if = "Option::is_none")]
	pub allowed_origins: Option<Vec<String>>,
	/// Whether the instance should operate in cookieless development mode (i.e. without third-party cookies). Deprecated: Please use `url_based_session_syncing` instead.
	#[serde(
		rename = "cookieless_dev",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub cookieless_dev: Option<Option<bool>>,
	/// Whether the instance should use URL-based session syncing in development mode (i.e. without third-party cookies).
	#[serde(
		rename = "url_based_session_syncing",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub url_based_session_syncing: Option<Option<bool>>,
	/// When password is required at the instance level, sets the preferred sign-in strategy surfaced to Clerk components. Has no effect when password is not required. Defaults to `password`. Set to an empty string to clear the override.
	#[serde(
		rename = "preferred_sign_in_strategy_when_password_required",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub preferred_sign_in_strategy_when_password_required: Option<Option<PreferredSignInStrategyWhenPasswordRequired>>,
}

impl UpdateInstanceRequest {
	pub fn new() -> UpdateInstanceRequest {
		UpdateInstanceRequest {
			test_mode: None,
			hibp: None,
			support_email: None,
			clerk_js_version: None,
			development_origin: None,
			allowed_origins: None,
			cookieless_dev: None,
			url_based_session_syncing: None,
			preferred_sign_in_strategy_when_password_required: None,
		}
	}
}
/// When password is required at the instance level, sets the preferred sign-in strategy surfaced to Clerk components. Has no effect when password is not required. Defaults to `password`. Set to an empty string to clear the override.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PreferredSignInStrategyWhenPasswordRequired {
	#[serde(rename = "password")]
	Password,
	#[serde(rename = "otp")]
	Otp,
	#[serde(rename = "")]
	Empty,
}

impl Default for PreferredSignInStrategyWhenPasswordRequired {
	fn default() -> PreferredSignInStrategyWhenPasswordRequired {
		Self::Password
	}
}
