/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSamlConnectionRequest {
	/// The name of the new SAML Connection
	#[serde(
		rename = "name",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub name: Option<Option<String>>,
	/// The domain to use for the new SAML Connection
	#[serde(
		rename = "domain",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub domain: Option<Option<String>>,
	/// The entity id as provided by the IdP
	#[serde(
		rename = "idp_entity_id",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub idp_entity_id: Option<Option<String>>,
	/// The SSO url as provided by the IdP
	#[serde(
		rename = "idp_sso_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub idp_sso_url: Option<Option<String>>,
	/// The x509 certificated as provided by the IdP
	#[serde(
		rename = "idp_certificate",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub idp_certificate: Option<Option<String>>,
	/// Activate or de-activate the SAML Connection
	#[serde(
		rename = "active",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub active: Option<Option<bool>>,
	/// Controls whether to update the user's attributes in each sign-in
	#[serde(
		rename = "sync_user_attributes",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub sync_user_attributes: Option<Option<bool>>,
}

impl UpdateSamlConnectionRequest {
	pub fn new() -> UpdateSamlConnectionRequest {
		UpdateSamlConnectionRequest {
			name: None,
			domain: None,
			idp_entity_id: None,
			idp_sso_url: None,
			idp_certificate: None,
			active: None,
			sync_user_attributes: None,
		}
	}
}
