/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateScimDirectoryRequest {
	/// A human-friendly name for the directory.
	#[serde(rename = "name", skip_serializing_if = "Option::is_none")]
	pub name: Option<String>,
	/// Whether the directory is enabled.
	#[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
	pub enabled: Option<bool>,
	/// The identity provider for this directory.
	#[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
	pub provider: Option<String>,
	/// Attribute-to-SCIM-path entries to merge into the directory's attribute mapping. Set a key to `null` to remove it from the mapping.
	#[serde(rename = "attribute_mapping", skip_serializing_if = "Option::is_none")]
	pub attribute_mapping: Option<std::collections::HashMap<String, String>>,
	/// Whether group-to-role mapping is enabled for this directory.
	#[serde(rename = "group_role_mapping_enabled", skip_serializing_if = "Option::is_none")]
	pub group_role_mapping_enabled: Option<bool>,
}

impl UpdateScimDirectoryRequest {
	pub fn new() -> UpdateScimDirectoryRequest {
		UpdateScimDirectoryRequest {
			name: None,
			enabled: None,
			provider: None,
			attribute_mapping: None,
			group_role_mapping_enabled: None,
		}
	}
}
