/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateApiKeyRequest {
	#[serde(
		rename = "claims",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub claims: Option<Option<serde_json::Value>>,
	#[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
	pub scopes: Option<Vec<String>>,
	#[serde(
		rename = "description",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub description: Option<Option<String>>,
	#[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
	pub subject: Option<String>,
	#[serde(
		rename = "seconds_until_expiration",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub seconds_until_expiration: Option<Option<f64>>,
}

impl UpdateApiKeyRequest {
	pub fn new() -> UpdateApiKeyRequest {
		UpdateApiKeyRequest {
			claims: None,
			scopes: None,
			description: None,
			subject: None,
			seconds_until_expiration: None,
		}
	}
}
