/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProductionInstanceDomainRequest {
    /// The new home URL of the production instance e.g. https://www.example.com
    #[serde(rename = "home_url", skip_serializing_if = "Option::is_none")]
    pub home_url: Option<String>,
}

impl UpdateProductionInstanceDomainRequest {
    pub fn new() -> UpdateProductionInstanceDomainRequest {
        UpdateProductionInstanceDomainRequest {
            home_url: None,
        }
    }
}


