/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerificationSaml {
	#[serde(rename = "object", skip_serializing_if = "Option::is_none")]
	pub object: Option<Object>,
	#[serde(rename = "status")]
	pub status: Status,
	#[serde(rename = "strategy")]
	pub strategy: Strategy,
	#[serde(
		rename = "external_verification_redirect_url",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub external_verification_redirect_url: Option<Option<String>>,
	#[serde(
		rename = "error",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub error: Option<Option<Box<models::ClerkError>>>,
	#[serde(
		rename = "expire_at",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub expire_at: Option<Option<i64>>,
	#[serde(rename = "attempts", deserialize_with = "Option::deserialize")]
	pub attempts: Option<i32>,
	#[serde(
		rename = "verified_at_client",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub verified_at_client: Option<Option<String>>,
}

impl VerificationSaml {
	pub fn new(status: Status, strategy: Strategy, attempts: Option<i32>) -> VerificationSaml {
		VerificationSaml {
			object: None,
			status,
			strategy,
			external_verification_redirect_url: None,
			error: None,
			expire_at: None,
			attempts,
			verified_at_client: None,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "verification_saml")]
	VerificationSaml,
}

impl Default for Object {
	fn default() -> Object {
		Self::VerificationSaml
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
	#[serde(rename = "unverified")]
	Unverified,
	#[serde(rename = "verified")]
	Verified,
	#[serde(rename = "failed")]
	Failed,
	#[serde(rename = "expired")]
	Expired,
	#[serde(rename = "transferable")]
	Transferable,
}

impl Default for Status {
	fn default() -> Status {
		Self::Unverified
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strategy {
	#[serde(rename = "saml")]
	Saml,
}

impl Default for Strategy {
	fn default() -> Strategy {
		Self::Saml
	}
}
