/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyTotp200Response {
	#[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
	pub verified: Option<bool>,
	#[serde(rename = "code_type", skip_serializing_if = "Option::is_none")]
	pub code_type: Option<CodeType>,
}

impl VerifyTotp200Response {
	pub fn new() -> VerifyTotp200Response {
		VerifyTotp200Response {
			verified: None,
			code_type: None,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CodeType {
	#[serde(rename = "totp")]
	Totp,
	#[serde(rename = "backup_code")]
	BackupCode,
}

impl Default for CodeType {
	fn default() -> CodeType {
		Self::Totp
	}
}
