/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerificationGoogleOneTap {
	#[serde(rename = "object", skip_serializing_if = "Option::is_none")]
	pub object: Option<Object>,
	#[serde(rename = "status")]
	pub status: Status,
	#[serde(rename = "strategy")]
	pub strategy: Strategy,
	#[serde(rename = "expire_at", deserialize_with = "Option::deserialize")]
	pub expire_at: Option<i32>,
	#[serde(rename = "attempts", deserialize_with = "Option::deserialize")]
	pub attempts: Option<i32>,
	#[serde(
		rename = "verified_at_client",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub verified_at_client: Option<Option<String>>,
	#[serde(
		rename = "error",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub error: Option<Option<Box<models::ClerkError>>>,
}

impl VerificationGoogleOneTap {
	pub fn new(status: Status, strategy: Strategy, expire_at: Option<i32>, attempts: Option<i32>) -> VerificationGoogleOneTap {
		VerificationGoogleOneTap {
			object: None,
			status,
			strategy,
			expire_at,
			attempts,
			verified_at_client: None,
			error: None,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "verification_google_one_tap")]
	VerificationGoogleOneTap,
}

impl Default for Object {
	fn default() -> Object {
		Self::VerificationGoogleOneTap
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
	#[serde(rename = "unverified")]
	Unverified,
	#[serde(rename = "verified")]
	Verified,
}

impl Default for Status {
	fn default() -> Status {
		Self::Unverified
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strategy {
	#[serde(rename = "google_one_tap")]
	GoogleOneTap,
}

impl Default for Strategy {
	fn default() -> Strategy {
		Self::GoogleOneTap
	}
}
