/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2025-04-10`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: 2026-05-12
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WaitlistEntry {
	#[serde(rename = "object")]
	pub object: Object,
	#[serde(rename = "id")]
	pub id: String,
	#[serde(rename = "email_address")]
	pub email_address: String,
	#[serde(rename = "status")]
	pub status: Status,
	/// Indicates if the waitlist entry is locked. Locked entries are being processed in a batch action and are unavailable for other actions.
	#[serde(rename = "is_locked", skip_serializing_if = "Option::is_none")]
	pub is_locked: Option<bool>,
	/// Unix timestamp of creation.
	#[serde(rename = "created_at")]
	pub created_at: i64,
	/// Unix timestamp of last update.
	#[serde(rename = "updated_at")]
	pub updated_at: i64,
	#[serde(
		rename = "invitation",
		default,
		with = "::serde_with::rust::double_option",
		skip_serializing_if = "Option::is_none"
	)]
	pub invitation: Option<Option<Box<models::Invitation>>>,
}

impl WaitlistEntry {
	pub fn new(object: Object, id: String, email_address: String, status: Status, created_at: i64, updated_at: i64) -> WaitlistEntry {
		WaitlistEntry {
			object,
			id,
			email_address,
			status,
			is_locked: None,
			created_at,
			updated_at,
			invitation: None,
		}
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
	#[serde(rename = "waitlist_entry")]
	WaitlistEntry,
}

impl Default for Object {
	fn default() -> Object {
		Self::WaitlistEntry
	}
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
	#[serde(rename = "pending")]
	Pending,
	#[serde(rename = "invited")]
	Invited,
	#[serde(rename = "rejected")]
	Rejected,
	#[serde(rename = "completed")]
	Completed,
}

impl Default for Status {
	fn default() -> Status {
		Self::Pending
	}
}
