/*
 * Clerk Backend API
 *
 * The Clerk REST Backend API, meant to be accessed by backend servers. Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Web3Wallet {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value. 
    #[serde(rename = "object")]
    pub object: Object,
    #[serde(rename = "web3_wallet")]
    pub web3_wallet: String,
    #[serde(rename = "verification", deserialize_with = "Option::deserialize")]
    pub verification: Option<Box<crate::models::Web3WalletVerification>>,
}

impl Web3Wallet {
    pub fn new(object: Object, web3_wallet: String, verification: Option<crate::models::Web3WalletVerification>) -> Web3Wallet {
        Web3Wallet {
            id: None,
            object,
            web3_wallet,
            verification: if let Some(x) = verification {Some(Box::new(x))} else {None},
        }
    }
}

/// String representing the object's type. Objects of the same type share the same value. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "web3_wallet")]
    Web3Wallet,
}

impl Default for Object {
    fn default() -> Object {
        Self::Web3Wallet
    }
}

